#pragma once
#include "MemoryHelpers.h"
#include <vector>

// PlayerData struct
struct PlayerData
{
	int PlayerID;
	uint32_t Coins;
	uint32_t unknown1;
	uint32_t unknown2;
	uint32_t ExperiencePoints;
	uint32_t Level;
	uint32_t unknown4; //Has something to do with towns people?
	uint32_t unknown5;
	uint32_t unknown6;
	uint32_t unknown7;
	uint32_t unknown8;
	uint32_t unknown9;
	int32_t unknown10;
	uint32_t unknown11;
	uint32_t unknown12;
	uint32_t unknown13;
	uint32_t unknown14;
	uint32_t unknown15;
	uint32_t unknown16;
	uint32_t unknown17;
	uint32_t unknown18;
	uint32_t unknown19;
	uint32_t unknown20;
	uint32_t unknown21;
	uint32_t unknown22;
	uint32_t unknown23;
};

struct CameraData
{
	float unknown1;
	float unknown2;
	int CameraMode; // the overhead view and the normal view is 2, tower of sour is 7 and the transformation is 4
};

struct Vector3
{
	float x;
	float y;
	float z;
};

struct EnityData
{
	int Entityoffset;
	Vector3 Position;
};

enum class ActorType
{
    Unknown,
    Pinata,
    Decor,
    Home,
    Shed,
    Seed,
    SeedPacket,
    Flower,
    Tree,
    LandType,
    Assessory,
    Fruit,
    Veggie,
    Egg,
    Crate,
    Helper,
	Ruffian,
    Shopkeeper,
    SpecialBuilding,
    Produse,
    Totem,
    Tool,
    Fence,
    Coin,
    Weed,
    Candy,
    LifeCandy,
    Paving,
    Flowerhead,
    Contract
};

enum class Accessibility {
    InGame,
    Cut,
    UnobtainableInGame
};

struct PinataIDs
{
	uint32_t ID;
	const char* Name;
    ActorType Type = ActorType::Unknown;
    Accessibility Accessibility = Accessibility::InGame;
};

inline DWORD* Test_a2;
inline int Test_a3;
inline bool Update = false;

inline bool g_Debug = false; // Debug mode


inline bool g_EasyBreakSickPinata = false;
inline bool g_EasyBreakItems = false;

inline PlayerData* g_PlayerDataPtr;
inline CameraData* g_CameraDataPtr;
inline std::vector<EnityData> g_EntityData;




//temporary variables for testing funtion inputs on tick without flooding the console (Render these in imgui)
inline int g_i1;
inline int g_i2;
inline int g_i3;
inline int g_i4;

inline float g_f1;
inline float g_f2;
inline float g_f3;
inline float g_f4;

inline char* g_c1;
inline char* g_c2;
inline char* g_c3;
inline char* g_c4;

// Function to set player coins
typedef char(__cdecl* SetPlayerCoinsF)(struct PlayerData*, uint32_t) noexcept;
inline SetPlayerCoinsF SetPlayerCoinsPtr = (SetPlayerCoinsF)GetVivaAddressPtr(0x0073FB80);
inline static void SetPlayerCoins(uint32_t Value) {
	if (g_PlayerDataPtr)
	{
		SetPlayerCoinsPtr(g_PlayerDataPtr, Value);
	}
}

//Unlimited Garden Space
inline static SimpleMemoryPatch g_UnlimitedGardenSpace = {
	0x7785D0,
		{0x53, 0x56, 0x8B, 0x74, 0x24, 0x10},
		{0xB8, 0x01, 0x00, 0x00, 0x00, 0xC3}
};

//Windowed mode 
// (This cant be set at runtime because its called at the beginning of the game,
// so this is just a example of how to use a complex patch)
//Though if we hook the main function we can set it before the game starts based on a config file
inline static ComplexMemoryPatch g_WindowedMode = {
	{
		{
			0x7D348D, 
				{0xC7, 0x46, 0x20, 0x00, 0x00, 0x00, 0x00}, 
				{0xC7, 0x46, 0x20, 0x01, 0x00, 0x00, 0x00}
		},

		{
			0x8C1700, 
				{0x68, 0x00, 0x00, 0x00, 0x80}, 
				{0x68, 0x00, 0x00, 0x8E, 0x00}
		}
	//We should add a anti lock mouse patch here
	//as well as a minimize window patch
	//and a resizeable window patch
	}
};



inline static std::vector<PinataIDs> g_PinataIDs = {
    {3, "Raisant", ActorType::Pinata, Accessibility::InGame},
    {5, "Badgesicle", ActorType::Pinata, Accessibility::InGame},
    {6, "Sherbat", ActorType::Pinata, Accessibility::InGame},
    {7, "Fizzlybear", ActorType::Pinata, Accessibility::InGame},
    {8, "Sweetooth", ActorType::Pinata, Accessibility::InGame},
    {9, "Buzzlegum", ActorType::Pinata, Accessibility::InGame},
    {10, "Black Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {11, "Taffly", ActorType::Pinata, Accessibility::InGame},
    {12, "Blue Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {13, "Twingersnap", ActorType::Pinata, Accessibility::InGame},
    {14, "Brown Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {15, "Galagoogoo", ActorType::Pinata, Accessibility::InGame},
    {16, "Buzzenge", ActorType::Pinata, Accessibility::InGame},
    {18, "Candary", ActorType::Pinata, Accessibility::InGame},
    {20, "Kittyfloss", ActorType::Pinata, Accessibility::InGame},
    {21, "Jameleon", ActorType::Pinata, Accessibility::InGame},
    {22, "Cluckles", ActorType::Pinata, Accessibility::InGame},
    {24, "Moozipan", ActorType::Pinata, Accessibility::InGame},
    {26, "Cocoadile", ActorType::Pinata, Accessibility::InGame},
    {27, "Crowla", ActorType::Pinata, Accessibility::InGame},
    {28, "Doenut", ActorType::Pinata, Accessibility::InGame},
    {30, "Barkbark", ActorType::Pinata, Accessibility::InGame},
    {32, "Dragonache", ActorType::Pinata, Accessibility::InGame},
    {33, "Dragumfly", ActorType::Pinata, Accessibility::InGame},
    {34, "Quackberry", ActorType::Pinata, Accessibility::InGame},
    {36, "Eaglair", ActorType::Pinata, Accessibility::InGame},
    {38, "Elephanilla", ActorType::Pinata, Accessibility::InGame},
    {39, "Reddhott", ActorType::Pinata, Accessibility::InGame},
    {40, "Salamango", ActorType::Pinata, Accessibility::InGame},
    {42, "Pigxie", ActorType::Pinata, Accessibility::InGame},
    {43, "Pretztail", ActorType::Pinata, Accessibility::InGame},
    {44, "Lickatoad", ActorType::Pinata, Accessibility::InGame},
    {52, "Juicygoose", ActorType::Pinata, Accessibility::InGame},
    {54, "Syrupent", ActorType::Pinata, Accessibility::InGame},
    {55, "Green Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {58, "Fudgehog", ActorType::Pinata, Accessibility::InGame},
    {59, "Chippopotamus", ActorType::Pinata, Accessibility::InGame},
    {60, "Horstachio", ActorType::Pinata, Accessibility::InGame},
    {62, "Fourheads", ActorType::Pinata, Accessibility::InGame},
    {63, "Lemmoning", ActorType::Pinata, Accessibility::Cut},
    {64, "Sour Lemmoning", ActorType::Pinata, Accessibility::Cut},
    {69, "Roario", ActorType::Pinata, Accessibility::InGame},
    {73, "Bonboon", ActorType::Pinata, Accessibility::InGame},
    {75, "Profitamole", ActorType::Pinata, Accessibility::InGame},
    {77, "Cinnamonkey", ActorType::Pinata, Accessibility::InGame},
    {78, "Moojo", ActorType::Pinata, Accessibility::Cut},
    {79, "Mothdrop", ActorType::Pinata, Accessibility::InGame},
    {80, "Mousemallow", ActorType::Pinata, Accessibility::InGame},
    {81, "Newtgat", ActorType::Pinata, Accessibility::InGame},
    {83, "Orange Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {87, "Parrybo", ActorType::Pinata, Accessibility::InGame},
    {88, "Polollybear", ActorType::Pinata, Accessibility::Cut},
    {89, "Pengum", ActorType::Pinata, Accessibility::Cut},
    {90, "Rashberry", ActorType::Pinata, Accessibility::InGame},
    {91, "Pudgeon", ActorType::Pinata, Accessibility::InGame},
    {92, "Lackatoad", ActorType::Pinata, Accessibility::InGame},
    {93, "Pink Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {94, "Ponocky", ActorType::Pinata, Accessibility::InGame},
    {95, "Purple Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {96, "Bunnycomb", ActorType::Pinata, Accessibility::InGame},
    {97, "Macaraccoon", ActorType::Pinata, Accessibility::InGame},
    {100, "Red Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {103, "Robean", ActorType::Pinata, Accessibility::Cut},
    {108, "Goobaa", ActorType::Pinata, Accessibility::InGame},
    {112, "Sparrowmint", ActorType::Pinata, Accessibility::InGame},
    {113, "Arocknid", ActorType::Pinata, Accessibility::InGame},
    {114, "Squazzil", ActorType::Pinata, Accessibility::InGame},
    {119, "Swanana", ActorType::Pinata, Accessibility::InGame},
    {126, "Chewnicorn", ActorType::Pinata, Accessibility::InGame},
    {127, "Sour Sherbat", ActorType::Pinata, Accessibility::InGame},
    {131, "White Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {133, "Mallowolf", ActorType::Pinata, Accessibility::InGame},
    {134, "Jeli", ActorType::Pinata, Accessibility::Cut},
    {135, "Whirlm", ActorType::Pinata, Accessibility::InGame},
    {136, "Flapjak", ActorType::Pinata, Accessibility::Cut},
    {137, "Yellow Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {138, "Zumbug", ActorType::Pinata, Accessibility::InGame},
    {146, "Sour Crowla", ActorType::Pinata, Accessibility::InGame},
    {147, "Sour Macaraccoon", ActorType::Pinata, Accessibility::InGame},
    {148, "Sour Cocoadile", ActorType::Pinata, Accessibility::InGame},
    {150, "Sour Profitamole", ActorType::Pinata, Accessibility::InGame},
    {155, "Sour Mallowolf", ActorType::Pinata, Accessibility::InGame},
    {156, "Sour Bonboon", ActorType::Pinata, Accessibility::InGame},
    {159, "Shellybean", ActorType::Pinata, Accessibility::InGame},
    {160, "Sour Shellybean", ActorType::Pinata, Accessibility::InGame},
    {171, "Crate1", ActorType::Crate, Accessibility::InGame},
    {172, "Crate (Xbox Live)"},
    {173, "Crate3", ActorType::Crate, Accessibility::InGame},
    {184, "Raisant Egg", ActorType::Egg, Accessibility::InGame},
    {186, "Egg2", ActorType::Egg, Accessibility::InGame},
    {187, "Egg3", ActorType::Egg, Accessibility::InGame},
    {188, "Egg4", ActorType::Egg, Accessibility::InGame},
    {189, "Egg5", ActorType::Egg, Accessibility::InGame},
    {192, "Egg6", ActorType::Egg, Accessibility::InGame},
    {194, "Egg7", ActorType::Egg, Accessibility::InGame},
    {195, "Egg8", ActorType::Egg, Accessibility::InGame},
    {196, "Egg9", ActorType::Egg, Accessibility::InGame},
    {198, "Egg10", ActorType::Egg, Accessibility::InGame},
    {200, "Egg11", ActorType::Egg, Accessibility::InGame},
    {201, "Egg12", ActorType::Egg, Accessibility::InGame},
    {202, "Egg13", ActorType::Egg, Accessibility::InGame },
    {205, "Egg14", ActorType::Egg, Accessibility::InGame },
    {206, "Egg15", ActorType::Egg, Accessibility::InGame },
    {207, "Egg16", ActorType::Egg, Accessibility::InGame },
    {209, "Egg17", ActorType::Egg, Accessibility::InGame },
    {211, "Egg18", ActorType::Egg, Accessibility::InGame },
    {212, "Egg19", ActorType::Egg, Accessibility::InGame },
    {213, "Egg20", ActorType::Egg, Accessibility::InGame },
    {215, "Egg21", ActorType::Egg, Accessibility::InGame },
    {217, "Egg22", ActorType::Egg, Accessibility::InGame },
    {218, "Egg23", ActorType::Egg, Accessibility::InGame },
    {219, "Egg24", ActorType::Egg, Accessibility::InGame },
    {221, "Egg25", ActorType::Egg, Accessibility::InGame },
    {222, "Egg26", ActorType::Egg, Accessibility::InGame },
    {223, "Egg27", ActorType::Egg, Accessibility::InGame },
    {231, "Egg28", ActorType::Egg, Accessibility::InGame },
    {233, "Egg29", ActorType::Egg, Accessibility::InGame },
    {237, "Egg30", ActorType::Egg, Accessibility::InGame },
    {238, "Egg31", ActorType::Egg, Accessibility::InGame },
    {239, "Egg32", ActorType::Egg, Accessibility::InGame },
    {240, "Egg33", ActorType::Egg, Accessibility::InGame },
    {248, "Egg34", ActorType::Egg, Accessibility::InGame },
    {252, "Egg35", ActorType::Egg, Accessibility::InGame },
    {254, "Egg36", ActorType::Egg, Accessibility::InGame },
    {256, "Egg37", ActorType::Egg, Accessibility::InGame },
    {258, "Egg38", ActorType::Egg, Accessibility::InGame },
    {259, "Egg39", ActorType::Egg, Accessibility::InGame },
    {260, "Egg40", ActorType::Egg, Accessibility::InGame },
    {266, "Egg41", ActorType::Egg, Accessibility::InGame },
    {269, "Egg42", ActorType::Egg, Accessibility::InGame },
    {270, "Egg43", ActorType::Egg, Accessibility::InGame },
    {271, "Egg44", ActorType::Egg, Accessibility::InGame },
    {273, "Egg45", ActorType::Egg, Accessibility::InGame },
    {275, "Egg46", ActorType::Egg, Accessibility::InGame },
    {276, "Egg47", ActorType::Egg, Accessibility::InGame },
    {279, "Egg48", ActorType::Egg, Accessibility::InGame },
    {287, "Egg49", ActorType::Egg, Accessibility::InGame },
    {291, "Egg50", ActorType::Egg, Accessibility::InGame },
    {292, "Egg51", ActorType::Egg, Accessibility::InGame },
    {293, "Egg52", ActorType::Egg, Accessibility::InGame },
    {298, "Egg53", ActorType::Egg, Accessibility::InGame },
    {306, "Egg54", ActorType::Egg, Accessibility::InGame },
    {307, "Cutscene Egg (Sour Sherbat)", ActorType::Egg, Accessibility::UnobtainableInGame },
    {311, "Egg55", ActorType::Egg, Accessibility::InGame },
    {312, "Egg56", ActorType::Egg, Accessibility::InGame },
    {314, "Egg57", ActorType::Egg, Accessibility::InGame },
    {317, "Egg58", ActorType::Egg, Accessibility::InGame },
    {319, "Egg59", ActorType::Egg, Accessibility::InGame },
    {320, "Shellybean Egg", ActorType::Egg, Accessibility::InGame},
    {332, "Acorn", ActorType::Fruit, Accessibility::InGame },
    {333, "Apple", ActorType::Fruit, Accessibility::InGame },
    {334, "Banana", ActorType::Fruit, Accessibility::InGame },
    {337, "Nightshade Berry", ActorType::Fruit, Accessibility::InGame },
    {338, "Fir Cone", ActorType::Fruit, Accessibility::InGame },
    {339, "Gem1", ActorType::Fruit, Accessibility::InGame },
    {340, "Hazelnut", ActorType::Fruit, Accessibility::InGame },
    {342, "Monkeynut", ActorType::Fruit, Accessibility::InGame },
    {346, "Blackberry", ActorType::Fruit, Accessibility::InGame },
    {347, "Gooseberry", ActorType::Fruit, Accessibility::InGame },
    {350, "Gem2", ActorType::Fruit, Accessibility::InGame },
    {351, "Gem3", ActorType::Fruit, Accessibility::InGame },
    {352, "Gem4", ActorType::Fruit, Accessibility::InGame },
    {353, "Gem5", ActorType::Fruit, Accessibility::InGame },
    {354, "Gem6", ActorType::Fruit, Accessibility::InGame },
    {361, "Weedling", ActorType::Helper, Accessibility::InGame },
    {362, "Leafos", ActorType::Helper, Accessibility::InGame },
    {363, "Ivor Bargain", ActorType::Shopkeeper, Accessibility::InGame },
    {364, "Storkos", ActorType::Helper, Accessibility::InGame },
    {365, "Sprinkling", ActorType::Helper, Accessibility::InGame },
    {366, "Seedos", ActorType::Helper, Accessibility::InGame },
    {367, "Bart", ActorType::Shopkeeper, Accessibility::InGame },
    {368, "Diggerling", ActorType::Helper, Accessibility::InGame },
    {369, "Ruffian1", ActorType::Ruffian, Accessibility::InGame },
    {370, "Ruffian2", ActorType::Ruffian, Accessibility::InGame },
    {371, "Ruffian3", ActorType::Ruffian, Accessibility::InGame },
    {372, "Ruffian4", ActorType::Ruffian, Accessibility::InGame },
    {373, "Doc Patchingo", ActorType::Shopkeeper, Accessibility::InGame },
    {376, "Gatherling", ActorType::Helper, Accessibility::InGame },
    {377, "Watchling1", ActorType::Helper, Accessibility::InGame },
    {378, "Night Watchling", ActorType::Helper, Accessibility::InGame },
    {380, "Willy", ActorType::Shopkeeper, Accessibility::InGame },
    {381, "Dastardos", ActorType::Helper, Accessibility::InGame },
    {382, "Professor Pester", ActorType::Ruffian, Accessibility::InGame },
    {399, "Carrot Seed", ActorType::Seed, Accessibility::InGame },
    {400, "Turnip Seed", ActorType::Seed, Accessibility::InGame },
    {402, "Pumpkin Seed", ActorType::Seed, Accessibility::InGame },
    {403, "Chili Seed", ActorType::Seed, Accessibility::InGame },
    {404, "Cutscene Seed (Carrot)", ActorType::Seed, Accessibility::UnobtainableInGame },
    {406, "Corn Seed", ActorType::Seed, Accessibility::InGame },
    {409, "Daisy Seed", ActorType::Seed, Accessibility::InGame },
    {410, "Buttercup Seed", ActorType::Seed, Accessibility::InGame },
    {411, "Bluebell Seed", ActorType::Seed, Accessibility::InGame },
    {412, "Poppy Seed", ActorType::Seed, Accessibility::InGame },
    {413, "Sunflower Seed", ActorType::Seed, Accessibility::InGame },
    {414, "Tulip Seed", ActorType::Seed, Accessibility::InGame },
    {415, "Snapdragon Seed", ActorType::Seed, Accessibility::InGame },
    {416, "Bird of Paradise", ActorType::Seed, Accessibility::InGame },
    {417, "Orchid Seed", ActorType::Seed, Accessibility::InGame },
    {428, "Watercress Seed", ActorType::Seed, Accessibility::InGame },
    {429, "Water Lily Seed", ActorType::Seed, Accessibility::InGame },
    {430, "Bullrush Seed", ActorType::Seed, Accessibility::InGame },
    {435, "Thistle Seed", ActorType::Seed, Accessibility::InGame },
    {436, "Poison Ivy Seed", ActorType::Seed, Accessibility::InGame },
    {437, "Toadstool Seed", ActorType::Seed, Accessibility::InGame },
    {438, "Venus Pinata Trap", ActorType::Seed, Accessibility::InGame },
    {446, "Apple Seed", ActorType::Seed, Accessibility::InGame },
    {447, "Hazelnut Seed", ActorType::Seed, Accessibility::InGame },
    {448, "Oak Seed", ActorType::Seed, Accessibility::InGame },
    {449, "Fir Seed", ActorType::Seed, Accessibility::InGame },
    {450, "Blackberry Seed", ActorType::Seed, Accessibility::InGame },
    {451, "Banana Seed", ActorType::Seed, Accessibility::InGame },
    {452, "Gooseberry Seed", ActorType::Seed, Accessibility::InGame },
    {453, "Gem Seed", ActorType::Seed, Accessibility::InGame },
    {455, "Monkeynut Seed", ActorType::Seed, Accessibility::InGame },
    {456, "Nightshade Seed", ActorType::Seed, Accessibility::InGame },
    {470, "Raisant Home", ActorType::Home, Accessibility::InGame },
    {472, "Badgesicle Home", ActorType::Home, Accessibility::InGame },
    {473, "Sherbat Home", ActorType::Home, Accessibility::InGame },
    {474, "Fizzlybear Home", ActorType::Home, Accessibility::InGame },
    {475, "Sweetooth Home", ActorType::Home, Accessibility::InGame },
    {476, "Buzzlegum Home", ActorType::Home, Accessibility::InGame },
    {478, "Taffly Home", ActorType::Home, Accessibility::InGame },
    {479, "Flutterscotch Home", ActorType::Home, Accessibility::InGame },
    {480, "Twingersnap Home", ActorType::Home, Accessibility::InGame },
    {481, "Honey hive", ActorType::Home, Accessibility::InGame },
    {482, "Galagoogoo Home", ActorType::Home, Accessibility::InGame },
    {483, "Buzzenge Home", ActorType::Home, Accessibility::InGame },
    {485, "Candary Home", ActorType::Home, Accessibility::InGame },
    {487, "Kittyfloss Home", ActorType::Home, Accessibility::InGame },
    {488, "Jameleon Home", ActorType::Home, Accessibility::InGame },
    {489, "Cluckles Home", ActorType::Home, Accessibility::InGame },
    {491, "Moozipan Home", ActorType::Home, Accessibility::InGame },
    {492, "Milking Shed", ActorType::SpecialBuilding, Accessibility::InGame },
    {493, "Cocoadile Home", ActorType::Home, Accessibility::InGame },
    {494, "Crowla Home", ActorType::Home, Accessibility::InGame },
    {495, "Doenut Home", ActorType::Home, Accessibility::InGame },
    {497, "Barkbark Home", ActorType::Home, Accessibility::InGame },
    {500, "Dragumfly Home", ActorType::Home, Accessibility::InGame },
    {501, "Quackberry Home", ActorType::Home, Accessibility::InGame },
    {503, "Eaglair Home", ActorType::Home, Accessibility::InGame },
    {505, "Elephanilla Home", ActorType::Home, Accessibility::InGame },
    {506, "Reddhott Home", ActorType::Home, Accessibility::InGame },
    {507, "Salamango Home", ActorType::Home, Accessibility::InGame },
    {509, "Mystery Home", ActorType::Home, Accessibility::InGame },
    {510, "Pretztail Home", ActorType::Home, Accessibility::InGame },
    {511, "Lickatoad Home", ActorType::Home, Accessibility::InGame },
    {519, "Juicygoose Home", ActorType::Home, Accessibility::InGame },
    {521, "Syrupent home", ActorType::Home, Accessibility::InGame },
    {525, "Fudgehog Home", ActorType::Home, Accessibility::InGame },
    {526, "Chippopotamus Home", ActorType::Home, Accessibility::InGame },
    {527, "Horstachio Home", ActorType::Home, Accessibility::InGame },
    {528, "Fourheads Home", ActorType::Home, Accessibility::InGame },
    {536, "Roario Home", ActorType::Home, Accessibility::InGame },
    {540, "Bonboon Home", ActorType::Home, Accessibility::InGame },
    {542, "Profitamole Home", ActorType::Home, Accessibility::InGame },
    {544, "Cinnamonkey Home", ActorType::Home, Accessibility::InGame },
    {546, "Mothdrop Home", ActorType::Home, Accessibility::InGame },
    {547, "Mousemallow Home", ActorType::Home, Accessibility::InGame },
    {548, "Newtgat Home", ActorType::Home, Accessibility::InGame },
    {554, "Parrybo Home", ActorType::Home, Accessibility::InGame },
    {557, "Rashberry Home", ActorType::Home, Accessibility::InGame },
    {558, "Pudgeon Home", ActorType::Home, Accessibility::InGame },
    {559, "Lackatoad Home", ActorType::Home, Accessibility::InGame },
    {561, "Ponocky Home", ActorType::Home, Accessibility::InGame },
    {563, "Bunnycomb Home", ActorType::Home, Accessibility::InGame },
    {564, "Macaraccoon Home", ActorType::Home, Accessibility::InGame },
    {575, "Goobaa Home", ActorType::Home, Accessibility::InGame },
    {576, "Shearing Shed", ActorType::Home, Accessibility::InGame },
    {579, "Sparrowmint Home", ActorType::Home, Accessibility::InGame },
    {580, "Arocknid Home", ActorType::Home, Accessibility::InGame },
    {581, "Squazzil Home", ActorType::Home, Accessibility::InGame },
    {586, "Swanana Home", ActorType::Home, Accessibility::InGame },
    {593, "Chewnicorn Home", ActorType::Home, Accessibility::InGame },
    {600, "Mallowolf Home", ActorType::Home, Accessibility::InGame },
    {602, "Whirlm Home", ActorType::Home, Accessibility::InGame },
    {605, "Zumbug Home", ActorType::Home, Accessibility::InGame },
    {606, "Shellybean Home", ActorType::Home, Accessibility::InGame },
    {607, "Mine", ActorType::SpecialBuilding, Accessibility::InGame },
    {613, "Helper Home", ActorType::SpecialBuilding, Accessibility::InGame },
    {618, "Soil", ActorType::LandType, Accessibility::InGame },
    {619, "Sand", ActorType::LandType, Accessibility::UnobtainableInGame },
    {620, "Snow", ActorType::LandType, Accessibility::UnobtainableInGame },
    {621, "Grass", ActorType::LandType, Accessibility::InGame },
    {622, "Mud", ActorType::LandType, Accessibility::InGame },
    {623, "Long Grass", ActorType::LandType, Accessibility::InGame },
    {624, "NULL1", ActorType::Unknown, Accessibility::UnobtainableInGame },
    {625, "NULL2", ActorType::Unknown, Accessibility::UnobtainableInGame },
    {626, "NULL3", ActorType::Unknown, Accessibility::UnobtainableInGame },
    {627, "Extra Garden Space", ActorType::LandType, Accessibility::InGame },
    {628, "Shallow Water", ActorType::LandType, Accessibility::InGame },
    {629, "Deep Water", ActorType::LandType, Accessibility::InGame },
    {630, "NULL4", ActorType::Unknown, Accessibility::UnobtainableInGame },
    {631, "Hard Soil", ActorType::LandType, Accessibility::InGame },
    {634, "Honey", ActorType::Produse, Accessibility::InGame },
    {635, "Milk", ActorType::Produse, Accessibility::InGame },
    {636, "Wool", ActorType::Produse, Accessibility::InGame },
    {640, "Rainbow Gem", ActorType::Produse, Accessibility::InGame },
    {644, "Cheese", ActorType::Produse, Accessibility::InGame },
    {645, "Bread", ActorType::Produse, Accessibility::InGame },
    {646, "Jack o' Lantern", ActorType::Produse, Accessibility::InGame },
    {647, "Jam", ActorType::Produse, Accessibility::InGame },
    {648, "Medicine", ActorType::Produse, Accessibility::InGame },
    {649, "Mushroom", ActorType::Produse, Accessibility::InGame },
    {650, "Sandwich", ActorType::Produse, Accessibility::InGame },
    {651, "Sapphire", ActorType::Produse, Accessibility::InGame },
    {652, "Diamond", ActorType::Produse, Accessibility::InGame },
    {653, "Mine Workings", ActorType::Produse, Accessibility::InGame },
    {654, "Gold Nugget", ActorType::Produse, Accessibility::InGame },
    {655, "Gold Flake", ActorType::Produse, Accessibility::InGame },
    {656, "Gooseberry Fool", ActorType::Produse, Accessibility::InGame },
    {657, "Peanut butter", ActorType::Produse, Accessibility::InGame },
    {658, "Banana Split", ActorType::Produse, Accessibility::InGame },
    {659, "Bone", ActorType::Produse, Accessibility::InGame },
    {660, "Carrot Cake", ActorType::Produse, Accessibility::InGame },
    {661, "Toffee Apple", ActorType::Produse, Accessibility::InGame },
    {662, "Emerald", ActorType::Produse, Accessibility::InGame },
    {665, "Firebrand", ActorType::Decor, Accessibility::InGame },
    {666, "Pirate Statue", ActorType::Decor, Accessibility::InGame },
    {671, "Bird and Bear Statue", ActorType::Decor, Accessibility::InGame },
    {674, "Birdbath", ActorType::Decor, Accessibility::InGame },
    {677, "Ornamental Stones", ActorType::Decor, Accessibility::InGame },
    {678, "Surfboard", ActorType::Decor, Accessibility::InGame },
    {679, "Windchime Mk1", ActorType::Decor, Accessibility::InGame },
    {680, "Hay Bale", ActorType::Decor, Accessibility::InGame },
    {681, "Milk Churn", ActorType::Decor, Accessibility::InGame },
    {684, "Fish Fountain", ActorType::Decor, Accessibility::InGame },
    {685, "Swan Fountain", ActorType::Decor, Accessibility::InGame },
    {686, "Glow Rocks", ActorType::Decor, Accessibility::InGame },
    {688, "Pile of Leaves", ActorType::Decor, Accessibility::InGame },
    {690, "Barrel", ActorType::Decor, Accessibility::InGame },
    {692, "Captains Cutlass", ActorType::Decor, Accessibility::InGame },
    {693, "Flower Carving", ActorType::Decor, Accessibility::InGame },
    {694, "Cartwheel", ActorType::Decor, Accessibility::InGame },
    {699, "Moon-on-a-Stick", ActorType::Decor, Accessibility::InGame },
    {700, "Tombstone", ActorType::Decor, Accessibility::InGame },
    {701, "Water Waiver", ActorType::Decor, Accessibility::InGame },
    {703, "Toxic Drum", ActorType::Decor, Accessibility::InGame },
    {704, "Sundial", ActorType::Decor, Accessibility::InGame },
    {707, "Lantern O' Loot", ActorType::Decor, Accessibility::InGame },
    {744, "Old Fence", ActorType::Decor, Accessibility::InGame },
    {745, "Ruined Building", ActorType::Decor, Accessibility::InGame },
    {746, "Building Remains", ActorType::Decor, Accessibility::InGame },
    {747, "Rock", ActorType::Decor, Accessibility::InGame },
    {748, "Broken Statue", ActorType::Decor, Accessibility::InGame },
    {749, "Tree Stump", ActorType::Decor, Accessibility::UnobtainableInGame },
    {750, "Rotten Tree", ActorType::Decor, Accessibility::InGame },
    {751, "Old Stump", ActorType::Decor, Accessibility::InGame },
    {752, "Wheel", ActorType::Decor, Accessibility::InGame },
    {755, "Dastardos Scarer", ActorType::Decor, Accessibility::InGame },
    {756, "Fir Tree Log", ActorType::Decor, Accessibility::InGame },
    {757, "Red Eye Rainbow", ActorType::Decor, Accessibility::InGame },
    {758, "Hollow Log", ActorType::Decor, Accessibility::UnobtainableInGame },
    {759, "Junk Drum", ActorType::Decor, Accessibility::UnobtainableInGame },
    {760, "Junk Skip", ActorType::Decor, Accessibility::UnobtainableInGame },
    {761, "Junk Coop", ActorType::Decor, Accessibility::UnobtainableInGame },
    {762, "Junk Pan", ActorType::Decor, Accessibility::UnobtainableInGame },
    {763, "Junk Tank", ActorType::Decor, Accessibility::UnobtainableInGame },
    {764, "Ruined Building", ActorType::Decor, Accessibility::UnobtainableInGame },
    {765, "Jar 'o' Light", ActorType::Decor, Accessibility::InGame },
    {766, "Oil Lamp", ActorType::Decor, Accessibility::InGame },
    {767, "Vase", ActorType::Decor, Accessibility::InGame },
    {768, "Wind Chime Mk2", ActorType::Decor, Accessibility::InGame },
    {769, "Sword Mk2", ActorType::Decor, Accessibility::InGame },
    {770, "Old Arcade Machine", ActorType::Decor, Accessibility::UnobtainableInGame },
    {793, "Title (Japan)", ActorType::Decor, Accessibility::UnobtainableInGame },
    {794, "Tower of Sour Base", ActorType::Totem, Accessibility::UnobtainableInGame },
    {795, "Sherbat Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {796, "Cocoadile Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {797, "Crowla Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {798, "Bonboon Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {799, "Profitamole Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {800, "Macaraccoon Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {801, "Shellybean Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {802, "Mallowolf Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {803, "Title (English)", ActorType::Decor, Accessibility::UnobtainableInGame },
    {806, "Rusty Watering Can", ActorType::Tool, Accessibility::InGame },
    {807, "Tin Watering Can", ActorType::Tool, Accessibility::InGame },
    {808, "Gold Watering Can", ActorType::Tool, Accessibility::InGame },
    {809, "Glass Watering Can", ActorType::Tool, Accessibility::InGame },
    {810, "Everpour 5000 Watering Can", ActorType::Tool, Accessibility::InGame },
    {811, "One Pour Wonder", ActorType::Tool, Accessibility::InGame },
    {828, "Grass Packet", ActorType::Tool, Accessibility::InGame },
    {829, "Long Grass Packet", ActorType::Tool, Accessibility::InGame },
    {830, "Sand Packet", ActorType::Tool, Accessibility::Cut },
    {831, "Snow Packet", ActorType::Tool, Accessibility::Cut },
    {850, "Wooden Fence", ActorType::Fence, Accessibility::InGame },
    {851, "Wooden Gate", ActorType::Fence, Accessibility::InGame },
    {852, "Hedge", ActorType::Fence, Accessibility::InGame },
    {854, "Stone Wall", ActorType::Fence, Accessibility::InGame },
    {855, "Iron Gate", ActorType::Fence, Accessibility::InGame },
    {856, "Oak Gate", ActorType::Fence, Accessibility::InGame },
    {857, "Wooden Picket Fence", ActorType::Fence, Accessibility::InGame },
    {858, "Wire Fence", ActorType::Fence, Accessibility::InGame },
    {859, "Iron Railings", ActorType::Fence, Accessibility::InGame },
    {864, "Bronze Chocolate Coin", ActorType::Coin, Accessibility::InGame },
    {865, "Silver Chocolate Coin", ActorType::Coin, Accessibility::InGame },
    {866, "Gold Chocolate Coin", ActorType::Coin, Accessibility::InGame },
    {867, "Big Gold Chocolate Coin", ActorType::Coin, Accessibility::InGame },
    {877, "Apple Tree1", ActorType::Tree, Accessibility::InGame },
    {878, "Apple Tree (Tiny)", ActorType::Tree, Accessibility::Cut },
    {879, "Hazel Tree", ActorType::Tree, Accessibility::InGame },
    {880, "Oak Tree", ActorType::Tree, Accessibility::InGame },
    {881, "Fir Tree", ActorType::Tree, Accessibility::InGame },
    {882, "Blackberry bush", ActorType::Tree, Accessibility::InGame },
    {883, "Banana Tree", ActorType::Tree, Accessibility::InGame },
    {884, "Gooseberry bush", ActorType::Tree, Accessibility::InGame },
    {885, "Gem Tree", ActorType::Tree, Accessibility::InGame },
    {887, "Monkeynut Tree", ActorType::Tree, Accessibility::InGame },
    {888, "Nightshade bush", ActorType::Tree, Accessibility::InGame },
   // {890, "Nightshade bush2", ActorType::Tree, Accessibility::InGame }, //Crashes
    {925, "Carrot Plant", ActorType::Flower, Accessibility::InGame },
    {926, "Turnip Plant", ActorType::Flower, Accessibility::InGame },
    {928, "Pumpkin Plant", ActorType::Flower, Accessibility::InGame },
    {929, "Chili Plant", ActorType::Flower, Accessibility::InGame },
    {932, "Corn Plant", ActorType::Flower, Accessibility::InGame },
    {933, "Orchids1 Plant", ActorType::Flower, Accessibility::InGame },
    {935, "Daisy Plant", ActorType::Flower, Accessibility::InGame },
    {936, "Buttercup Plant", ActorType::Flower, Accessibility::InGame },
    {937, "Bluebell Plant", ActorType::Flower, Accessibility::InGame },
    {938, "Poppy Plant", ActorType::Flower, Accessibility::InGame },
    {939, "Sunflower Plant", ActorType::Flower, Accessibility::InGame },
    {940, "Tulip Plant", ActorType::Flower, Accessibility::InGame },
	{ 941, "Snapdragon Plant", ActorType::Flower, Accessibility::InGame },
    {942, "Bird of Paradise Plant", ActorType::Flower, Accessibility::InGame},
    {943, "Orchids2 Plant", ActorType::Flower, Accessibility::InGame},
    //{945, "Orchids3 Plant", ActorType::Flower, Accessibility::InGame}, //Crashes
    {954, "Watercress Plant", ActorType::Flower, Accessibility::InGame},
    {955, "Water Lily Plant", ActorType::Flower, Accessibility::InGame},
    {956, "Bullrush Plant", ActorType::Flower, Accessibility::InGame},
    {961, "Thistle Plant", ActorType::Weed, Accessibility::InGame },
    {962, "Poison Ivy Plant", ActorType::Weed, Accessibility::InGame },
    {963, "Toadstool Plant", ActorType::Weed, Accessibility::InGame },
    {964, "Venus Pinata Trap Plant", ActorType::Weed, Accessibility::InGame },
    {966, "Orchids4 Plant", ActorType::Flower, Accessibility::InGame },
    {977, "Freebie Shovel Head", ActorType::Tool, Accessibility::InGame },
    {978, "Seed Shovel Head", ActorType::Tool, Accessibility::InGame },
    {979, "Pond Shovel Head", ActorType::Tool, Accessibility::InGame },
    {980, "Treecutter Shovel Head", ActorType::Tool, Accessibility::InGame },
    {981, "Dastardos Head", ActorType::Tool, Accessibility::InGame },
    {999, "Freebie Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1000, "Iron Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1001, "Bronze Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1002, "Silver Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1003, "Gold Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1004, "Platinum Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1021, "Chocolate Sniffer", ActorType::Tool, Accessibility::InGame },
    {1218, "Pinata Candy", ActorType::Candy, Accessibility::InGame },
    {1220, "Sour Candy", ActorType::Candy, Accessibility::InGame },
    {1235, "Happy Candy", ActorType::Candy, Accessibility::InGame },
    {1236, "Joy Candy", ActorType::Candy, Accessibility::InGame },
    {1238, "Romance Candy", ActorType::Candy, Accessibility::InGame },
    {1283, "Slab Paving", ActorType::Paving, Accessibility::InGame },
    {1284, "Stone Paving", ActorType::Paving, Accessibility::InGame },
    {1285, "Block Paving", ActorType::Paving, Accessibility::InGame },
    {1286, "Crazy Paving", ActorType::Paving, Accessibility::InGame },
    {1288, "Cobblestones", ActorType::Paving, Accessibility::InGame },
    {1291, "Showbiz", ActorType::Paving, Accessibility::InGame },
    {1292, "Octagonal Paving", ActorType::Paving, Accessibility::InGame },
    {1306, "Raisant Site", ActorType::Shed, Accessibility::InGame },
    {1308, "Badgesicle Site", ActorType::Shed, Accessibility::InGame },
    {1309, "Sherbat Site", ActorType::Shed, Accessibility::InGame },
    {1310, "Fizzlybear Site", ActorType::Shed, Accessibility::InGame },
    {1311, "Sweetooth Site", ActorType::Shed, Accessibility::InGame },
    {1312, "Buzzlegum Site", ActorType::Shed, Accessibility::InGame },
    {1314, "Taffly Site", ActorType::Shed, Accessibility::InGame },
    {1315, "Flutterscotch Site", ActorType::Shed, Accessibility::InGame },
    {1316, "Twingersnap Site", ActorType::Shed, Accessibility::InGame },
    {1317, "Honey Hive Site", ActorType::Shed, Accessibility::InGame },
    {1318, "Galagoogoo Site", ActorType::Shed, Accessibility::InGame },
    {1319, "Buzzenge Site", ActorType::Shed, Accessibility::InGame },
    {1321, "Candary Site", ActorType::Shed, Accessibility::InGame },
    {1323, "Kittyfloss Site", ActorType::Shed, Accessibility::InGame },
    {1324, "Jameleon Site", ActorType::Shed, Accessibility::InGame },
    {1325, "Cluckles Site", ActorType::Shed, Accessibility::InGame },
    {1327, "Moozipan Site", ActorType::Shed, Accessibility::InGame },
    {1328, "Moozipan Shed Site", ActorType::Shed, Accessibility::InGame },
    {1329, "Cocoadile Site", ActorType::Shed, Accessibility::InGame },
    {1330, "Crowla Site", ActorType::Shed, Accessibility::InGame },
    {1331, "Doenut Site", ActorType::Shed, Accessibility::InGame },
    {1333, "Barkbark Site", ActorType::Shed, Accessibility::InGame },
    {1336, "Dragumfly Site", ActorType::Shed, Accessibility::InGame },
    {1337, "Quackberry Site", ActorType::Shed, Accessibility::InGame },
    {1339, "Eaglair Site", ActorType::Shed, Accessibility::InGame },
    {1341, "Elephanilla Site", ActorType::Shed, Accessibility::InGame },
    {1342, "Reddhott Site", ActorType::Shed, Accessibility::InGame },
    {1343, "Salamango Site", ActorType::Shed, Accessibility::InGame },
    {1345, "Pigxie Building Site", ActorType::Shed, Accessibility::InGame },
    {1346, "Pretztail Site", ActorType::Shed, Accessibility::InGame },
    {1347, "Lickatoad Site", ActorType::Shed, Accessibility::InGame },
    {1355, "Juicygoose Site", ActorType::Shed, Accessibility::InGame },
    {1357, "Syrupent Site", ActorType::Shed, Accessibility::InGame },
    {1361, "Fudgehog Site", ActorType::Shed, Accessibility::InGame },
    {1362, "Chippopotamus Site", ActorType::Shed, Accessibility::InGame },
    {1363, "Horstachio Site", ActorType::Shed, Accessibility::InGame },
    {1364, "Fourheads Site", ActorType::Shed, Accessibility::InGame },
    {1372, "Roario Site", ActorType::Shed, Accessibility::InGame },
    {1376, "Bonboon Site", ActorType::Shed, Accessibility::InGame },
    {1378, "Profitamole Site", ActorType::Shed, Accessibility::InGame },
    {1380, "Cinnamonkey Site", ActorType::Shed, Accessibility::InGame },
    {1382, "Mothdrop Site", ActorType::Shed, Accessibility::InGame },
    {1383, "Mousemallow Site", ActorType::Shed, Accessibility::InGame },
    {1384, "Newtgat Site", ActorType::Shed, Accessibility::InGame },
    {1390, "Parrybo Site", ActorType::Shed, Accessibility::InGame },
    {1393, "Rashberry Site", ActorType::Shed, Accessibility::InGame },
    {1394, "Pudgeon Site", ActorType::Shed, Accessibility::InGame },
    {1395, "Lackatoad Site", ActorType::Shed, Accessibility::InGame },
    {1397, "Ponocky Site", ActorType::Shed, Accessibility::InGame },
    {1399, "Bunnycomb Site", ActorType::Shed, Accessibility::InGame },
    {1400, "Macaraccoon Site", ActorType::Shed, Accessibility::InGame },
    {1411, "Goobaa Site", ActorType::Shed, Accessibility::InGame },
    {1412, "Goobaa Shed Site", ActorType::Shed, Accessibility::InGame },
    {1415, "Sparrowmint Site", ActorType::Shed, Accessibility::InGame },
    {1416, "Spider Site", ActorType::Shed, Accessibility::InGame },
    {1417, "Squazzil Site", ActorType::Shed, Accessibility::InGame },
    {1422, "Swanana Site", ActorType::Shed, Accessibility::InGame },
    {1429, "Chewnicorn Site", ActorType::Shed, Accessibility::InGame },
    {1436, "Mallowolf Site", ActorType::Shed, Accessibility::InGame },
    {1438, "Whirlm Site", ActorType::Shed, Accessibility::InGame },
    {1441, "Zumbug Site", ActorType::Shed, Accessibility::InGame },
    {1442, "Shellybean Site", ActorType::Shed, Accessibility::InGame },
    {1443, "Mine Site", ActorType::Shed, Accessibility::InGame },
    {1449, "Helper House Site", ActorType::Shed, Accessibility::InGame },
    {1454, "Daisy Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1455, "Buttercup Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1456, "Bluebell Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1457, "Poppy Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1458, "Sunflower Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1459, "Tulip Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1460, "Snapdragon Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1461, "Bird of Paradise Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1462, "Orchid Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1464, "Watercress Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1465, "Water Lily Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1466, "Bulrush Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1467, "Thistle Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1468, "Poison Ivy Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1470, "Venus Pinata Trap Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1488, "Carrot", ActorType::Veggie, Accessibility::InGame },
    {1489, "Turnip", ActorType::Veggie, Accessibility::InGame },
    {1491, "Pumpkin", ActorType::Veggie, Accessibility::InGame },
    {1492, "Chili", ActorType::Veggie, Accessibility::InGame },
    {1495, "Corn", ActorType::Veggie, Accessibility::InGame },
    {1501, "Raisant Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1502, "Badgesicle Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1503, "Sherbat Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1504, "Fizzlybear Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1505, "Sweetooth Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1506, "Buzzlegum Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1507, "Black Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1508, "Taffly Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1509, "Blue Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1510, "Twingersnap Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1511, "Brown Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1512, "Galagoogoo Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1513, "Buzzenge Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1514, "Candary Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1515, "Kittyfloss Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1516, "Jameleon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1517, "Cluckles Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1518, "Moozipan Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1519, "Cocoadile Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1520, "Crowla Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1521, "Doenut Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1522, "Barkbark Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1523, "Dragonache Life Candy", ActorType::LifeCandy, Accessibility::UnobtainableInGame },
    {1524, "Dragumfly Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1525, "Quackberry Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1526, "Eaglair Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1527, "Elephanilla Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1528, "Reddhott Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1529, "Salamango Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1530, "Pigxie Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1531, "Pretztail Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1532, "Lickatoad Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1533, "Raisant Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1535, "Juicygoose Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1536, "Syrupent Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1537, "Green Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1538, "Fudgehog Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1539, "Chippopotamus Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1540, "Horstachio Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1541, "Fourheads Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1542, "Roario Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1543, "Bonboon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1544, "Profitamole Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1545, "Cinnamonkey Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1546, "Mothdrop Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1547, "Mousemallow Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1548, "Newtgat Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1549, "Orange Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1550, "Parrybo Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1551, "Rashberry Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1552, "Pudgeon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1553, "Lackatoad Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1554, "Pink Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1555, "Ponocky Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1556, "Purple Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1557, "Bunnycomb Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1558, "Macaraccoon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1559, "Red Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1560, "Salamango Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1561, "Goobaa Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1562, "Sparrowmint Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1563, "Arocknid Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1564, "Squazzil Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1565, "Swanana Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1566, "Chewnicorn Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1567, "Sour Sherbat Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1568, "White Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1569, "Mallowolf Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1570, "Whirlm Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1571, "Yellow Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1572, "Zumbug Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1574, "Sour Crowla Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1575, "Sour Macaraccoon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1576, "Sour Cocoadile Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1577, "Sour Profitamole Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1578, "Sour Mallowolf Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1579, "Sour Bonboon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1580, "Shellybean Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1581, "Sour Shellybean Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1585, "Lottie", ActorType::Shopkeeper, Accessibility::InGame },
    {1586, "Fannie", ActorType::Shopkeeper, Accessibility::InGame },
    {1587, "Doc Patchingo", ActorType::Shopkeeper, Accessibility::InGame },
    {1588, "Arfur", ActorType::Shopkeeper, Accessibility::InGame },
    {1589, "Willy", ActorType::Shopkeeper, Accessibility::InGame },
    {1590, "Miss Petula", ActorType::Shopkeeper, Accessibility::InGame },
    {1591, "Ivor Beggar", ActorType::Helper, Accessibility::InGame },
    {1592, "Bart", ActorType::Shopkeeper, Accessibility::InGame },
    {1593, "Gretchen", ActorType::Shopkeeper, Accessibility::InGame },
    {1600, "Red Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1601, "Yellow Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1602, "Blue Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1603, "Green Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1604, "Purple Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1605, "Orange Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1606, "Brown Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1607, "Cocoadile Tears Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1608, "Special Mix Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1622, "Sprinkling Contract", ActorType::Contract, Accessibility::InGame },
    {1623, "Weedling Contract", ActorType::Contract, Accessibility::InGame },
    {1624, "Watchling1 Contract", ActorType::Contract, Accessibility::InGame },
    {1625, "Gatherling Contract", ActorType::Contract, Accessibility::InGame },
    {1626, "Diggerling Contract", ActorType::Contract, Accessibility::InGame },
    {1627, "Watchling2 Contract", ActorType::Contract, Accessibility::InGame },
    {1660, "Retro Disco Wig", ActorType::Assessory, Accessibility::InGame },
    {1661, "Breegull Carrier", ActorType::Assessory, Accessibility::InGame },
    {1662, "Shark Tooth Necklace", ActorType::Assessory, Accessibility::InGame },
    {1663, "Cool Shades", ActorType::Assessory, Accessibility::InGame },
    {1664, "Howdy Pardner Hat", ActorType::Assessory, Accessibility::InGame },
    {1665, "Doenut Stalker", ActorType::Assessory, Accessibility::InGame },
    {1670, "Yokel Teeth", ActorType::Assessory, Accessibility::InGame },
    {1672, "Yee-haw Hat", ActorType::Assessory, Accessibility::InGame },
    {1673, "Se or Sombrero", ActorType::Assessory, Accessibility::InGame },
    {1674, "Pillager's Helmet", ActorType::Assessory, Accessibility::InGame },
    {1675, "Thunder Cut", ActorType::Assessory, Accessibility::InGame },
    {1676, "Beanie Cap", ActorType::Assessory, Accessibility::InGame },
    {1677, "Weather-Girl Wig", ActorType::Assessory, Accessibility::InGame },
    {1678, "Diggerling Helmet Mk1", ActorType::Assessory, Accessibility::InGame },
    {1679, "Gas Mask", ActorType::Assessory, Accessibility::InGame },
    {1680, "Party Horns", ActorType::Assessory, Accessibility::InGame },
    {1682, "Caterpillars", ActorType::Assessory, Accessibility::InGame },
    {1684, "Super Hero Mask", ActorType::Assessory, Accessibility::InGame },
    {1685, "School Cap", ActorType::Assessory, Accessibility::InGame },
    {1686, "Baseball Cap", ActorType::Assessory, Accessibility::InGame },
    {1688, "Tiara of Tranquility", ActorType::Assessory, Accessibility::InGame },
    {1689, "Slim Tache", ActorType::Assessory, Accessibility::InGame },
    {1690, "Spiked Collar", ActorType::Assessory, Accessibility::InGame },
    {1691, "Geek Glasses", ActorType::Assessory, Accessibility::InGame },
    {1692, "Reporter's Camera", ActorType::Assessory, Accessibility::InGame },
    {1693, "Bling Teeth", ActorType::Assessory, Accessibility::InGame },
    {1694, "Bow", ActorType::Assessory, Accessibility::InGame },
    {1695, "Fez", ActorType::Assessory, Accessibility::InGame },
    {1696, "Fake Winner's Rosette", ActorType::Assessory, Accessibility::InGame },
    {1697, "Diamond Choker", ActorType::Assessory, Accessibility::InGame },
    {1698, "Blackeye Patch", ActorType::Assessory, Accessibility::InGame },
    {1699, "Tap Shoes", ActorType::Assessory, Accessibility::InGame },
    {1700, "Ballet Shoes", ActorType::Assessory, Accessibility::InGame },
    {1701, "Crown", ActorType::Assessory, Accessibility::InGame },
    {1702, "Handlebar Mustache", ActorType::Assessory, Accessibility::InGame },
    {1703, "Football Helmet", ActorType::Assessory, Accessibility::InGame },
    {1704, "Sweaty Wrist Band", ActorType::Assessory, Accessibility::InGame },
    {1705, "Bling Bangle", ActorType::Assessory, Accessibility::InGame },
    {1706, "Beaded Wig", ActorType::Assessory, Accessibility::InGame },
    {1708, "Secret Agent Bowtie", ActorType::Assessory, Accessibility::InGame },
    {1709, "Bling Bracelet", ActorType::Assessory, Accessibility::InGame },
    {1710, "Crystal Broach", ActorType::Assessory, Accessibility::InGame },
    {1711, "Bunnycomb Ears", ActorType::Assessory, Accessibility::InGame },
    {1712, "Bushy Moustache", ActorType::Assessory, Accessibility::InGame },
    {1713, "Cook Hat", ActorType::Assessory, Accessibility::InGame },
    {1714, "The Von Ghoul", ActorType::Assessory, Accessibility::InGame },
    {1715, "Yee-haw Boots", ActorType::Assessory, Accessibility::InGame },
    {1716, "Butcha's", ActorType::Assessory, Accessibility::InGame },
    {1717, "Diamond Necklace", ActorType::Assessory, Accessibility::InGame },
    {1718, "Combat Boots", ActorType::Assessory, Accessibility::InGame },
    {1720, "Romance Earrings", ActorType::Assessory, Accessibility::InGame },
    {1721, "Mermaid Earrings", ActorType::Assessory, Accessibility::InGame },
    {1722, "Big Bling Earrings", ActorType::Assessory, Accessibility::InGame },
    {1724, "Big Jolly Lips", ActorType::Assessory, Accessibility::InGame },
    {1725, "Comedian's Nose", ActorType::Assessory, Accessibility::InGame },
    {1726, "Buck Teeth", ActorType::Assessory, Accessibility::InGame },
    {1728, "Soccer Boots", ActorType::Assessory, Accessibility::InGame },
    {1729, "Squazzil Hat", ActorType::Assessory, Accessibility::InGame },
    {1730, "DanceGlow", ActorType::Assessory, Accessibility::InGame },
    {1731, "Pendant Necklace", ActorType::Assessory, Accessibility::InGame },
    {1732, "Halo of Hardness", ActorType::Assessory, Accessibility::InGame },
    {1733, "Safety Helmet", ActorType::Assessory, Accessibility::InGame },
    {1734, "Sweaty Head Band", ActorType::Assessory, Accessibility::InGame },
    {1735, "Breegull Waders", ActorType::Assessory, Accessibility::InGame },
    {1737, "Leafos Medallion", ActorType::Assessory, Accessibility::InGame },
    {1739, "Toff Monocle", ActorType::Assessory, Accessibility::InGame },
    {1740, "Astro-Walkers", ActorType::Assessory, Accessibility::InGame },
    {1741, "Halloween Bolts", ActorType::Assessory, Accessibility::InGame },
    {1742, "Bling Nose-Ring", ActorType::Assessory, Accessibility::InGame },
    {1743, "Dellmonty", ActorType::Assessory, Accessibility::InGame },
    {1745, "Mermaid Necklace", ActorType::Assessory, Accessibility::InGame },
    {1747, "Tussle Tricorn", ActorType::Assessory, Accessibility::InGame },
    {1748, "Rashberry Hat", ActorType::Assessory, Accessibility::InGame },
    {1749, "Rashberry Helmet", ActorType::Assessory, Accessibility::InGame },
    {1750, "Reading Glasses", ActorType::Assessory, Accessibility::InGame },
    {1751, "Red Nose", ActorType::Assessory, Accessibility::InGame },
    {1752, "Robber's Mask", ActorType::Assessory, Accessibility::InGame },
    {1753, "Extreme Sports Goggles", ActorType::Assessory, Accessibility::InGame },
    {1754, "Santa Hat", ActorType::Assessory, Accessibility::InGame },
    {1755, "Non-Resident Scarf", ActorType::Assessory, Accessibility::InGame },
    {1756, "Sea-Shell Collar", ActorType::Assessory, Accessibility::InGame },
    {1757, "Bunnycomb Slippers", ActorType::Assessory, Accessibility::InGame },
    {1758, "Snow Shoes", ActorType::Assessory, Accessibility::InGame },
    {1759, "Belly-Splash Specials", ActorType::Assessory, Accessibility::InGame },
    {1760, "Granny's Tache", ActorType::Assessory, Accessibility::InGame },
    {1761, "Funky Tie", ActorType::Assessory, Accessibility::InGame },
    {1762, "Conga's Top Hat", ActorType::Assessory, Accessibility::InGame },
    {1763, "Breegull Turbo Trainers", ActorType::Assessory, Accessibility::InGame },
    {1765, "Dastardos Scarf", ActorType::Assessory, Accessibility::InGame },
    {1766, "Bell", ActorType::Assessory, Accessibility::InGame },
    {1767, "Bonnet", ActorType::Assessory, Accessibility::InGame },
    {1768, "Buzzlegum Keeper Hat", ActorType::Assessory, Accessibility::InGame },
    {1769, "Buttercup Hair Flower", ActorType::Assessory, Accessibility::InGame },
    {1770, "Daisy Hair Flower", ActorType::Assessory, Accessibility::InGame },
    {1771, "Bling Earrings", ActorType::Assessory, Accessibility::InGame },
    {1772, "Not-so-Bling Earrings", ActorType::Assessory, Accessibility::InGame },
    {1773, "Pendant Earrings", ActorType::Assessory, Accessibility::InGame },
    {1774, "Pearly Bracelet", ActorType::Assessory, Accessibility::InGame },
    {1775, "Poppy Hair Flower", ActorType::Assessory, Accessibility::InGame },
    {1777, "Sunflower Hair Flower", ActorType::Assessory, Accessibility::InGame },
    {1778, "Student's Hat", ActorType::Assessory, Accessibility::InGame },
    {1779, "Comedian's Choice", ActorType::Assessory, Accessibility::InGame },
    {1780, "Strong 'n' Macho", ActorType::Assessory, Accessibility::InGame },
    {1781, "Soupswill Cook Hat", ActorType::Assessory, Accessibility::InGame },
    {1782, "Tail Bow", ActorType::Assessory, Accessibility::InGame },
    {1783, "Super Hero Belt", ActorType::Assessory, Accessibility::InGame },
    {1784, "Fruity Hat", ActorType::Assessory, Accessibility::InGame },
    {1785, "Mr. Pants Hat", ActorType::Assessory, Accessibility::InGame },
    {1786, "Sailor Hat", ActorType::Assessory, Accessibility::InGame },
    {1787, "Conkerific Helmet", ActorType::Assessory, Accessibility::InGame },
    {1788, "Vela Wig", ActorType::Assessory, Accessibility::InGame },
    {1789, "Juno Helmet", ActorType::Assessory, Accessibility::InGame },
    {1790, "Grunty Hat", ActorType::Assessory, Accessibility::InGame },
    {1791, "Jam-Jars Hat", ActorType::Assessory, Accessibility::InGame },
    {1792, "Binner's Hat", ActorType::Assessory, Accessibility::InGame },
    {1793, "Princess Hat", ActorType::Assessory, Accessibility::InGame },
    {1794, "Von Ghoul Helmet", ActorType::Assessory, Accessibility::InGame },
    {1795, "Sabreman Helmet", ActorType::Assessory, Accessibility::InGame },
    {1796, "Ortho's Spare Hat", ActorType::Assessory, Accessibility::InGame },
    {1797, "Knight Helmet", ActorType::Assessory, Accessibility::InGame },
    {1798, "Headphones", ActorType::Assessory, Accessibility::InGame },
    {1799, "Jiggy Earrings", ActorType::Assessory, Accessibility::InGame },
    {1800, "Lupus Ears", ActorType::Assessory, Accessibility::InGame },
    {1801, "Disco Shades", ActorType::Assessory, Accessibility::InGame },
    {1802, "Flying Goggles", ActorType::Assessory, Accessibility::InGame },
    {1803, "Bottles' Glasses", ActorType::Assessory, Accessibility::InGame },
    {1804, "Romantic Flower", ActorType::Assessory, Accessibility::InGame },
    {1805, "Battletoad Bracelets", ActorType::Assessory, Accessibility::InGame },
    {1806, "Prisoner Bracelet", ActorType::Assessory, Accessibility::InGame },
    {1807, "Rashberry Badge", ActorType::Assessory, Accessibility::InGame },
    {1808, "Clockwork Key", ActorType::Assessory, Accessibility::InGame },
    {1809, "Kameo Wings", ActorType::Assessory, Accessibility::InGame },
    {1810, "Fake Fin", ActorType::Assessory, Accessibility::InGame },
    {1811, "Flamenco Shoes", ActorType::Assessory, Accessibility::InGame },
    {1812, "Ash Slippers", ActorType::Assessory, Accessibility::InGame }
};

