#pragma once
#include "MemoryHelpers.h"
#include <vector>

inline float g_Time = 0.0f; //Delta time between frames
inline bool g_UpdateTime = false; //Set to true when g_Time is updated

inline int RESULT_4B5B90 = 0; //Used to            debug a1
inline int RESULT_80E820 = 0; //Used to debug   step 1
inline int RESULT_81A9C0 = 0; //Used to debug   step 2
inline int RESULT_957750 = 0; //Used to debug   step 3
inline int RESULT_7738F0 = 0; //Used to debug (TimeContext)

// PlayerData struct
struct PlayerData
{
	int PlayerID;
	uint32_t Coins;
	uint32_t unknown1;
	uint32_t unknown2;
	uint32_t ExperiencePoints;
	uint32_t Level;
	uint32_t unknown4; //Has something to do with towns people?
	uint32_t unknown5;
	uint32_t unknown6;
	uint32_t unknown7;
	uint32_t unknown8;
	uint32_t unknown9;
	int32_t unknown10;
	uint32_t unknown11;
	uint32_t unknown12;
	uint32_t unknown13;
	uint32_t unknown14;
	uint32_t unknown15;
	uint32_t unknown16;
	uint32_t unknown17;
	uint32_t unknown18;
	uint32_t unknown19;
	uint32_t unknown20;
	uint32_t unknown21;
	uint32_t unknown22;
	uint32_t unknown23;
};

struct CameraData
{
	float unknown1;
	float unknown2;
	int CameraMode; // the overhead view and the normal view is 2, tower of sour is 7 and the transformation is 4
};

struct Vector3
{
	float x;
	float y;
	float z;
};

struct EnityData
{
	int Entityoffset;
	Vector3 Position;
};

enum class ActorType
{
    Unknown,
    Pinata,
    Decor,
    Home,
    Shed,
    Seed,
    SeedPacket,
    Flower,
    Tree,
    LandType,
    Assessory,
    Fruit,
    Veggie,
    Egg,
    Crate,
    Helper,
	Ruffian,
    Shopkeeper,
    SpecialBuilding,
    Produse,
    Totem,
    Tool,
    Fence,
    Coin,
    Weed,
    Candy,
    LifeCandy,
    Paving,
    Flowerhead,
    Contract
};

enum class Accessibility {
    InGame,
    Cut,
    UnobtainableInGame
};

struct PinataIDs
{
	uint32_t ID;
	const char* Name;
    ActorType Type = ActorType::Unknown;
    Accessibility Accessibility = Accessibility::InGame;
};

inline DWORD* Test_a2;
inline int Test_a3;
inline bool Update = false;

inline bool g_Debug = false; // Debug mode


inline bool g_EasyBreakSickPinata = false;
inline bool g_EasyBreakItems = false;

inline PlayerData* g_PlayerDataPtr;
inline CameraData* g_CameraDataPtr;
inline std::vector<EnityData> g_EntityData;




//temporary variables for testing funtion inputs on tick without flooding the console (Render these in imgui)
inline int g_i1;
inline int g_i2;
inline int g_i3;
inline int g_i4;

inline float g_f1;
inline float g_f2;
inline float g_f3;
inline float g_f4;

inline char* g_c1;
inline char* g_c2;
inline char* g_c3;
inline char* g_c4;

// Function to set player coins
typedef char(__cdecl* SetPlayerCoinsF)(struct PlayerData*, uint32_t) noexcept;
inline SetPlayerCoinsF SetPlayerCoinsPtr = (SetPlayerCoinsF)GetVivaAddressPtr(0x0073FB80);
inline static void SetPlayerCoins(uint32_t Value) {
	if (g_PlayerDataPtr)
	{
		SetPlayerCoinsPtr(g_PlayerDataPtr, Value);
	}
}

//Unlimited Garden Space
inline static SimpleMemoryPatch g_UnlimitedGardenSpace = {
	"Unlimited Garden Space",
	0x7785D0,
		{0x53, 0x56, 0x8B, 0x74, 0x24, 0x10},
		{0xB8, 0x01, 0x00, 0x00, 0x00, 0xC3}
};

inline static SimpleMemoryPatch g_AlwaysWildcard = {
    "Always Wildcard",
    0x4DEEA7,
        {0x68, 0x11, 0x27},
        {0x68, 0x00, 0x00}
};

//00531231	0xa	D8 5D 00 DF E0 F6 C4 01 75 5A 	90 90 90 90 90 90 90 90 90 90  Instant Pinata Growth
inline static SimpleMemoryPatch g_InstantPinataGrowth = {
    "Instant Pinata Growth",
    0x531231,
        {0xD8, 0x5D, 0x00, 0xDF, 0xE0, 0xF6, 0xC4, 0x01, 0x75, 0x5A},
		{0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90}
};

//Rather then checking if the player has friends we just force it to know they dont
inline static SimpleMemoryPatch g_FixCrates = {
	"Fix Crates",
    0x849A25,
    {0x74},
	{0xEB}
};


inline uint16_t g_GrassLevel = 128; //Default grass level

//Ultra Grass aka 128 layers of grass shells
inline ComplexMemoryPatch g_UltraGrass = {
    {
        {
            "Remove Check for Grass Quality",
            0x6F50B1,
                {0x8B, 0x44, 0x8C, 0x04, 0x83, 0xF8, 0x0C, 0x7E, 0x05, 0x8D, 0x43, 0x0B},
                {0xB8, 0x00, 0x00, 0x00, 0x00, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90}
        },

        {
            "Remove Set Grass Quality",
            0x6F50C9,
                {0xA3, 0x54, 0xE7, 0xBA, 0x00},
			    {0x90, 0x90, 0x90, 0x90, 0x90}

        }
    }
    
};
        

//Windowed mode 
// (This cant be set at runtime because its called at the beginning of the game,
// so this is just a example of how to use a complex patch)
//Though if we hook the main function we can set it before the game starts based on a config file
inline static ComplexMemoryPatch g_WindowedMode = {
	{
		{
			"WindowMode Patch 1",
			0x7D348D, 
				{0xC7, 0x46, 0x20, 0x00, 0x00, 0x00, 0x00}, 
				{0xC7, 0x46, 0x20, 0x01, 0x00, 0x00, 0x00}
		},

		{
			"WindowMode Patch 2",
			0x8C1700, 
				{0x68, 0x00, 0x00, 0x00, 0x80}, 
				{0x68, 0x00, 0x00, 0x8E, 0x00}
		}
	//We should add a anti lock mouse patch here
	//as well as a minimize window patch
	//and a resizeable window patch
	}
};


inline static const char** g_IDNames = new const char* [1907] {
"aRTrigger",
"aNull_0",
"Animal_aaaaaa",
"Animal_ant",
"Animal_beetle",
"Animal_badger",
"Animal_bat",
"Animal_bear",
"Animal_beaver",
"Animal_bee",
"Animal_blackbutterfly",
"Animal_bluebottle",
"Animal_bluebutterfly",
"Animal_boomslang",
"Animal_brownbutterfly",
"Animal_bushbaby",
"Animal_buzzard",
"Animal_spare90",
"Animal_canary",
"Animal_spare89",
"Animal_cat",
"Animal_chameleon",
"Animal_chicken",
"Animal_camel",
"Animal_cow",
"Animal_spare87",
"Animal_crocodile",
"Animal_crow",
"Animal_deer",
"Animal_spare86",
"Animal_dog",
"Animal_spare85",
"Animal_dragon",
"Animal_dragonfly",
"Animal_duck",
"Animal_spare84",
"Animal_eagle",
"Animal_spare83",
"Animal_elephant",
"Animal_firefly",
"Animal_firesalamander",
"Animal_spare81",
"Animal_flyingpig",
"Animal_fox",
"Animal_frog",
"Animal_gecko",
"Animal_gerbil",
"Animal_spare80",
"Animal_spare79",
"Animal_spare78",
"Animal_spare76",
"Animal_spare75",
"Animal_goose",
"Animal_spare74",
"Animal_grasssnake",
"Animal_greenbutterfly",
"Animal_spare73",
"Animal_spare72",
"Animal_hedgehog",
"Animal_hippo",
"Animal_horse",
"Animal_hyena",
"Animal_hydra",
"Animal_lemming",
"Animal_lemmingpest",
"Animal_spare67",
"Animal_spare66",
"Animal_spare65",
"Animal_spare64",
"Animal_lion",
"Animal_spare63",
"Animal_spare62",
"Animal_spare61",
"Animal_mandrill",
"Animal_spare60",
"Animal_mole",
"Animal_spare59",
"Animal_monkey",
"Animal_moose",
"Animal_moth",
"Animal_mouse",
"Animal_newt",
"Animal_spare57",
"Animal_orangebutterfly",
"Animal_ostrich",
"Animal_spare55",
"Animal_spare54",
"Animal_parrot",
"Animal_polarbear",
"Animal_penguin",
"Animal_pig",
"Animal_pigeon",
"Animal_poisonfrog",
"Animal_pinkbutterfly",
"Animal_pony",
"Animal_purplebutterfly",
"Animal_rabbit",
"Animal_raccoon",
"Animal_spare50",
"Animal_spare49",
"Animal_redbutterfly",
"Animal_spare48",
"Animal_spare47",
"Animal_robin",
"Animal_spare45",
"Animal_spare44",
"Animal_salamander",
"Animal_spare43",
"Animal_sheep",
"Animal_scorpion",
"Animal_scorpionpest",
"Animal_spare40",
"Animal_sparrow",
"Animal_spider",
"Animal_squirrel",
"Animal_spare39",
"Animal_spare38",
"Animal_spare37",
"Animal_spare36",
"Animal_swan",
"Animal_spare35",
"Animal_spare34",
"Animal_spare33",
"Animal_spare32",
"Animal_spare31",
"Animal_spare30",
"Animal_unicorn",
"Animal_batpest",
"Animal_spare29",
"Animal_vulture",
"Animal_spare27",
"Animal_whitebutterfly",
"Animal_spare26",
"Animal_wolf",
"Animal_yeti",
"Animal_worm",
"Animal_yak",
"Animal_yellowbutterfly",
"Animal_zebra",
"Animal_slugpest",
"Animal_spare23",
"Animal_spare22",
"Animal_spare21",
"Animal_spare20",
"Animal_spare19",
"Animal_spare18",
"Animal_crowpest",
"Animal_raccoonpest",
"Animal_crocodilepest",
"Animal_spare17",
"Animal_molepest",
"Animal_spare16",
"Animal_spare15",
"Animal_spare14",
"Animal_spare13",
"Animal_wolfpest",
"Animal_mandrillpest",
"Animal_spare12",
"Animal_spare11",
"Animal_snail",
"Animal_snailpest",
"Animal_spare3",
"Animal_spare4",
"Animal_spare5",
"Animal_spare6",
"Animal_spare7",
"Animal_spare8",
"Animal_spare9",
"Animal_graysquirrel",
"Animal_zzzzzz",
"Crate_aaaaaa",
"Crate_regular",
"Crate_received",
"Crate_factory",
"Crate_spare3",
"Crate_spare4",
"Crate_spare5",
"Crate_spare6",
"Crate_spare7",
"Crate_spare8",
"Crate_spare9",
"Crate_spare10",
"Crate_zzzzzz",
"Egg_aaaaaa",
"Egg_ant",
"Egg_spare11",
"Egg_badger",
"Egg_bat",
"Egg_bear",
"Egg_beaver",
"Egg_bee",
"Egg_spare12",
"Egg_bluebottle",
"Egg_bluebutterfly",
"Egg_boomslang",
"Egg_bushbaby",
"Egg_buzzard",
"Egg_spare14",
"Egg_canary",
"Egg_spare15",
"Egg_cat",
"Egg_chameleon",
"Egg_chicken",
"Egg_spare16",
"Egg_spare17",
"Egg_crocodile",
"Egg_crow",
"Egg_deer",
"Egg_spare18",
"Egg_dog",
"Egg_spare19",
"Egg_dragon",
"Egg_dragonfly",
"Egg_duck",
"Egg_spare21",
"Egg_eagle",
"Egg_spare22",
"Egg_elephant",
"Egg_firefly",
"Egg_firesalamander",
"Egg_spare24",
"Egg_flyingpig",
"Egg_fox",
"Egg_frog",
"Egg_spare25",
"Egg_spare26",
"Egg_spare27",
"Egg_spare28",
"Egg_spare29",
"Egg_spare30",
"Egg_spare31",
"Egg_goose",
"Egg_spare32",
"Egg_grasssnake",
"Egg_greenbutterfly",
"Egg_spare33",
"Egg_spare34",
"Egg_hedgehog",
"Egg_hippo",
"Egg_horse",
"Egg_hydra",
"Egg_spare36",
"Egg_spare37",
"Egg_spare38",
"Egg_spare39",
"Egg_spare40",
"Egg_spare41",
"Egg_spare42",
"Egg_lion",
"Egg_spare43",
"Egg_spare44",
"Egg_spare45",
"Egg_mandrill",
"Egg_spare46",
"Egg_mole",
"Egg_spare47",
"Egg_monkey",
"Egg_spare48",
"Egg_moth",
"Egg_mouse",
"Egg_newt",
"Egg_spare49",
"Egg_orangebutterfly",
"Egg_spare50",
"Egg_spare51",
"Egg_spare52",
"Egg_parrot",
"Egg_spare53",
"Egg_spare54",
"Egg_pig",
"Egg_pigeon",
"Egg_poisonfrog",
"Egg_spare55",
"Egg_pony",
"Egg_purplebutterfly",
"Egg_rabbit",
"Egg_raccoon",
"Egg_spare56",
"Egg_spare57",
"Egg_redbutterfly",
"Egg_spare58",
"Egg_spare59",
"Egg_spare60",
"Egg_spare61",
"Egg_spare62",
"Egg_space102",
"Egg_spare63",
"Egg_sheep",
"Egg_spare64",
"Egg_spare65",
"Egg_spare66",
"Egg_sparrow",
"Egg_spider",
"Egg_squirrel",
"Egg_spare67",
"Egg_spare68",
"Egg_spare69",
"Egg_spare70",
"Egg_swan",
"Egg_spare71",
"Egg_spare72",
"Egg_spare73",
"Egg_spare74",
"Egg_spare75",
"Egg_spare76",
"Egg_spare77",
"Egg_unicorn",
"Egg_batpest",
"Egg_spare78",
"Egg_spare79",
"Egg_spare80",
"Egg_whitebutterfly",
"Egg_wolf",
"Egg_spare81",
"Egg_worm",
"Egg_spare82",
"Egg_yellowbutterfly",
"Egg_zebra",
"Egg_spare1",
"Egg_cow",
"Egg_snail",
"Egg_spare2",
"Egg_spare3",
"Egg_spare4",
"Egg_spare5",
"Egg_spare6",
"Egg_spare7",
"Egg_spare8",
"Egg_spare9",
"Egg_spare10",
"Egg_zzzzzz",
"Fruit_aaaaaa",
"Fruit_acorn",
"Fruit_apple",
"Fruit_banana",
"Fruit_cherry",
"Fruit_coconut",
"Fruit_deadlynightshade",
"Fruit_fircone",
"Fruit_gem",
"Fruit_hazelnut",
"Fruit_helper",
"Fruit_monkeynut",
"Fruit_orange",
"Fruit_raspberry",
"Fruit_hollyberry",
"Fruit_blackberry",
"Fruit_gooseberry",
"Fruit_cucumber",
"Fruit_biftreetest",
"Fruit_bluegem",
"Fruit_greengem",
"Fruit_purplegem",
"Fruit_redgem",
"Fruit_yellowgem",
"Fruit_spare7",
"Fruit_spare8",
"Fruit_spare9",
"Fruit_hippyapple",
"Fruit_zzzzzz",
"Helper_aaaaaa",
"Helper_weeder",
"Helper_dedos",
"Helper_beggartrader",
"Helper_stork",
"Helper_waterer",
"Helper_seedos",
"Helper_tinker",
"Helper_miner",
"Helper_ruffian3",
"Helper_ruffian1",
"Helper_ruffian2",
"Helper_ruffian4",
"Helper_doctor",
"Helper_petshopowner",
"Helper_spare15",
"Helper_harvester",
"Helper_groundskeeper",
"Helper_groundskeepernight",
"Helper_jardiniero",
"Helper_builder",
"Helper_dastardos",
"Helper_professor",
"Helper_spare23",
"Helper_spare24",
"Helper_spare25",
"Helper_spare26",
"Helper_spare27",
"Helper_spare28",
"Helper_spare29",
"Helper_spare30",
"Helper_spare31",
"Helper_spare32",
"Helper_spare33",
"Helper_spare34",
"Helper_spare35",
"Helper_spare36",
"Helper_zzzzzz",
"Seed_aaaaaa",
"Seed_carrot",
"Seed_turnip",
"Seed_spare3",
"Seed_pumpkin",
"Seed_chilli",
"Seed_testveg",
"Seed_nstestveg",
"Seed_maize",
"Seed_radish",
"Seed_yam",
"Seed_daisy",
"Seed_buttercup",
"Seed_bluebell",
"Seed_poppy",
"Seed_sunflower",
"Seed_tulip",
"Seed_snapdragon",
"Seed_birdofparadiseplant",
"Seed_orchid",
"Seed_testflower",
"Seed_snowdrop",
"Seed_cactus",
"Seed_spare5",
"Seed_spare6",
"Seed_spare7",
"Seed_spare8",
"Seed_spare9",
"Seed_spare10",
"Seed_blackbuttercup",
"Seed_watercress",
"Seed_waterlily",
"Seed_bulrush",
"Seed_spare12",
"Seed_spare13",
"Seed_spare14",
"Seed_spare15",
"Seed_thistle",
"Seed_poisonivy",
"Seed_toadstool",
"Seed_venusflytrap",
"Seed_tumbleweed",
"Seed_fireweed",
"Seed_spare18",
"Seed_spare19",
"Seed_spare20",
"Seed_spare21",
"Seed_test",
"Seed_apple",
"Seed_hazelnut",
"Seed_oak",
"Seed_fir",
"Seed_blackberrybush",
"Seed_banana",
"Seed_gooseberrybush",
"Seed_gem",
"Seed_helper",
"Seed_monkeynut",
"Seed_nightshadebush",
"Seed_nstest",
"Seed_hippyapple",
"Seed_hollybush",
"Seed_orange",
"Seed_spart25",
"Seed_spare26",
"Seed_workeb1",
"Seed_workeb2",
"Seed_zzzzzz",
"SeedHole_aaaaaa",
"SeedHole",
"SeedHole_zzzzzz",
"Home_aaaaaa",
"Home_ant",
"Home_gym",
"Home_badger",
"Home_bat",
"Home_bear",
"Home_beaver",
"Home_bee",
"Home_beetle",
"Home_bluebottle",
"Home_butterfly",
"Home_boomslang",
"Home_beeshed",
"Home_bushbaby",
"Home_buzzard",
"Home_spare13",
"Home_canary",
"Home_spare14",
"Home_cat",
"Home_chameleon",
"Home_chicken",
"Home_spare15",
"Home_cow",
"Home_cowshed",
"Home_crocodile",
"Home_crow",
"Home_deer",
"Home_spare17",
"Home_dog",
"Home_spare18",
"Home_dragon",
"Home_dragonfly",
"Home_duck",
"Home_spare19",
"Home_eagle",
"Home_spare20",
"Home_elephant",
"Home_firefly",
"Home_firesalamander",
"Home_spare22",
"Home_flyingpig",
"Home_fox",
"Home_frog",
"Home_spare23",
"Home_spare24",
"Home_spare25",
"Home_spare26",
"Home_spare27",
"Home_spare28",
"Home_spare29",
"Home_goose",
"Home_spare30",
"Home_grasssnake",
"Home_spare11",
"Home_spare32",
"Home_spare33",
"Home_hedgehog",
"Home_hippo",
"Home_horse",
"Home_hydra",
"Home_spare35",
"Home_spare36",
"Home_spare37",
"Home_spare38",
"Home_spare39",
"Home_spare40",
"Home_spare41",
"Home_lion",
"Home_spare42",
"Home_spare43",
"Home_spare44",
"Home_mandrill",
"Home_spare45",
"Home_mole",
"Home_spare46",
"Home_monkey",
"Home_spare47",
"Home_moth",
"Home_mouse",
"Home_newt",
"Home_spare48",
"Home_spare49",
"Home_spare50",
"Home_spare51",
"Home_spare52",
"Home_parrot",
"Home_spare53",
"Home_spare54",
"Home_pig",
"Home_pigeon",
"Home_poisonfrog",
"Home_spare55",
"Home_pony",
"Home_spare86",
"Home_rabbit",
"Home_raccoon",
"Home_spare56",
"Home_spare57",
"Home_spare58",
"Home_spare59",
"Home_spare60",
"Home_spare61",
"Home_spare62",
"Home_spare63",
"Home_salamander",
"Home_spare64",
"Home_sheep",
"Home_sheepshed",
"Home_spare66",
"Home_spare67",
"Home_sparrow",
"Home_spider",
"Home_squirrel",
"Home_spare68",
"Home_spare69",
"Home_spare70",
"Home_spare71",
"Home_swan",
"Home_spare72",
"Home_spare73",
"Home_spare74",
"Home_spare75",
"Home_spare76",
"Home_spare77",
"Home_unicorn",
"Home_spare87",
"Home_spare78",
"Home_spare79",
"Home_spare80",
"Home_spare81",
"Home_spare82",
"Home_wolf",
"Home_spare83",
"Home_worm",
"Home_spare84",
"Home_spare85",
"Home_zebra",
"Home_snail",
"Home_helpermine",
"Home_animalgym",
"Home_seedos",
"Home_storkos",
"Home_dastardos",
"Home_dedos",
"Home_helperhomeone",
"Home_spare9",
"Home_spare10",
"Home_zzzzzz",
"Surface_aaaaaa",
"Surface_soil",
"Surface_sand",
"Surface_snow",
"Surface_grass",
"Surface_mud",
"Surface_grasslong",
"Surface_slabs",
"Surface_gravel",
"Surface_boundary",
"Surface_exterior",
"Surface_shallowWater",
"Surface_deepWater",
"Surface_plants",
"Surface_hardsoil",
"Surface_zzzzzz",
"Produce_aaaaaa",
"Produce_honey",
"Produce_milk",
"Produce_wool",
"Produce_dung",
"Produce_goldegg",
"Produce_spare6",
"Produce_rainbowgem",
"Produce_crown",
"Produce_clothes",
"Produce_toffee",
"Produce_cheese",
"Produce_bread",
"Produce_jackolantern",
"Produce_jam",
"Produce_medicine",
"Produce_mushroom",
"Produce_sandwich",
"Produce_sapphire",
"Produce_diamond",
"Produce_minemud",
"Produce_largegoldnugget",
"Produce_smallgoldnugget",
"Produce_gooseberrypie",
"Produce_peanutbutter",
"Produce_bananasplit",
"Produce_bone",
"Produce_carrotcake",
"Produce_toffeeapple",
"Produce_emerald",
"Produce_zzzzzz",
"Prop_aaaaaa",
"Prop_lantern",
"Prop_statue",
"Prop_patioheater",
"Prop_perimeterstone",
"Prop_gravestone",
"Prop_dedoslawn",
"Prop_banjostatue",
"Prop_japaneseornament",
"Prop_plantstunter",
"Prop_birdbath1",
"Prop_birdbath2",
"Prop_watertrough",
"Prop_housestones",
"Prop_surfboard",
"Prop_windchime",
"Prop_haybail",
"Prop_milkchurn",
"Prop_log",
"Prop_smallfountain",
"Prop_fountain1",
"Prop_fountain2",
"Prop_glowrock",
"Prop_lavapool",
"Prop_leafpile",
"Prop_hydrapot",
"Prop_barrel",
"Prop_bamboopole",
"Prop_sword",
"Prop_woodenflower",
"Prop_cartwheel",
"Prop_oillamp",
"Prop_lamppost",
"Prop_glowglobe",
"Prop_jamjarcandle",
"Prop_moonlantern",
"Prop_tombstone",
"Prop_flag1",
"Prop_rainbow2",
"Prop_toxicbarrel",
"Prop_sundial1",
"Prop_sundial2",
"Prop_horselantern",
"Prop_minerslantern",
"Prop_flag2",
"Prop_flag3",
"Prop_flag4",
"Prop_roadsign1",
"Prop_roadsign2",
"Prop_roadsign3",
"Prop_boulders1",
"Prop_boulders2",
"Prop_stonehenge",
"Prop_lolly1",
"Prop_lolly2",
"Prop_lolly3",
"Prop_wirehearts",
"Prop_scarecrow",
"Prop_pantsstatue",
"Prop_sabremanstatue",
"Prop_kameostatue",
"Prop_jetpacstatue",
"Prop_cooperstatue",
"Prop_jinjostatue",
"Prop_chimney",
"Prop_windflower",
"Prop_post1",
"Prop_post2",
"Prop_windturbine",
"Prop_wishingwell",
"Prop_lawnmower",
"Prop_gnome",
"Prop_gift",
"Prop_shoppingbasket",
"Prop_journal",
"Prop_spade",
"Prop_romancesweet",
"Prop_background_prop",
"Prop_gazebo",
"Prop_pot1",
"Prop_gardenjunk80",
"Prop_gardenjunk81",
"Prop_gardenjunk82",
"Prop_gardenjunk83",
"Prop_gardenjunk84",
"Prop_gardenjunk85",
"Prop_gardenjunk86",
"Prop_gardenjunk87",
"Prop_gardenjunk88",
"Prop_gardenjunk89",
"Prop_gardenjunk90",
"Prop_mumbostatue",
"Prop_firtreelog",
"Prop_rainbow",
"Prop_appletreelog",
"Prop_junkdrum",
"Prop_junkskip",
"Prop_junkhomechicken",
"Prop_junkfryingpan",
"Prop_junkhomespider",
"Prop_junkhomemandrill",
"Prop_jamjar",
"Prop_oillmap",
"Prop_vase",
"Prop_windchime2",
"Prop_sword2",
"Prop_gbtgarcademachine",
"Prop_gardenjunk107",
"Prop_gardenjunk108",
"Prop_gardenjunk109",
"Prop_gardenjunk110",
"Prop_gardenjunk111",
"Prop_gardenjunk112",
"Prop_gardenjunk113",
"Prop_gardenjunk114",
"Prop_gardenjunk115",
"Prop_gardenjunk116",
"Prop_gardenjunk117",
"Prop_gardenjunk118",
"Prop_gardenjunk119",
"Prop_perimeterstone1",
"Prop_perimeterstone2",
"Prop_perimeterstone3",
"Prop_perimeterstone4",
"Prop_perimeterstone5",
"Prop_pot2",
"Prop_windsock",
"Prop_sculpture1",
"Prop_sculpture2",
"Prop_logojp",
"Prop_totembase",
"Prop_totembat",
"Prop_totemcrocodile",
"Prop_totemcrow",
"Prop_totemmandrill",
"Prop_totemmole",
"Prop_totemraccoon",
"Prop_totemsnail",
"Prop_totemwolf",
"Prop_logo",
"Prop_zzzzzz",
"WateringCan_aaaaaa",
"WateringCan_1",
"WateringCan_2",
"WateringCan_3",
"WateringCan_4",
"WateringCan_5",
"WateringCan_6",
"WateringCan_7",
"WateringCan_8",
"WateringCan_9",
"WateringCan_10",
"WateringCan_11",
"WateringCan_12",
"WateringCan_13",
"WateringCan_14",
"WateringCan_15",
"WateringCan_16",
"WateringCan_17",
"WateringCan_18",
"WateringCan_19",
"WateringCan_20",
"WateringCan_zzzzzz",
"Packet_aaaaaa",
"Packet_grass",
"Packet_grasslong",
"Packet_sand",
"Packet_snow",
"Packet_5",
"Packet_6",
"Packet_7",
"Packet_8",
"Packet_9",
"Packet_10",
"Packet_11",
"Packet_12",
"Packet_13",
"Packet_14",
"Packet_15",
"Packet_16",
"Packet_17",
"Packet_18",
"Packet_19",
"Packet_20",
"Packet_zzzzzz",
"Fence_aaaaaa",
"Fence_twobar",
"Fence_twobargate",
"Fence_hedge",
"Fence_herringbone",
"Fence_stone",
"Fence_irongate",
"Fence_oakgate",
"Fence_picket",
"Fence_wire",
"Fence_iron",
"Fence_velvetrope",
"Fence_spare10",
"Fence_zzzzzz",
"Money_aaaaaa",
"Money_bronze",
"Money_silver",
"Money_gold",
"Money_biggold",
"Money_spare4",
"Money_spare5",
"Money_spare6",
"Money_spare7",
"Money_spare8",
"Money_spare9",
"Money_spare10",
"Money_zzzzzz",
"BifTree_aaaaaa",
"BifTree_test",
"BifTree_apple",
"BifTree_hazelnut",
"BifTree_oak",
"BifTree_fir",
"BifTree_blackberrybush",
"BifTree_banana",
"BifTree_gooseberrybush",
"BifTree_gem",
"BifTree_helper",
"BifTree_monkeynut",
"BifTree_nightshadebush",
"BifTree_nstest",
"BifTree_hollybush",
"BifTree_orange",
"BifTree_spare1",
"BifTree_spart2",
"BifTree_spare3",
"BifTree_spare4",
"BifTree_spare5",
"BifTree_hippyapple",
"BifTree_spare6",
"BifTree_spare7",
"BifTree_spare8",
"BifTree_spare9",
"BifTree_spare10",
"BifTree_spare11",
"BifTree_spare12",
"BifTree_spare13",
"BifTree_spare14",
"BifTree_zzzzzz",
"CameraTarget_aaaaaa",
"CameraTarget",
"CameraTarget_zzzzzz",
"FruitPoint_aaaaaa",
"FruitPoint",
"FruitPoint_zzzzzz",
"Camera_aaaaaa",
"Camera",
"Camera_zzzzzz",
"Fighter_aaaaaa",
"Fighter",
"Fighter_zzzzzz",
"Background_aaaaaa",
"Background",
"Background_garden",
"Background_zzzzzz",
"BifPlant_aaaaaa",
"BifPlant_carrot",
"BifPlant_turnip",
"BifPlant_spare3",
"BifPlant_pumpkin",
"BifPlant_chilli",
"BifPlant_testveg",
"BifPlant_nstestveg",
"BifPlant_maize",
"BifPlant_radish",
"BifPlant_yam",
"BifPlant_daisy",
"BifPlant_buttercup",
"BifPlant_bluebell",
"BifPlant_poppy",
"BifPlant_sunflower",
"BifPlant_tulip",
"BifPlant_snapdragon",
"BifPlant_birdofparadiseplant",
"BifPlant_orchid",
"BifPlant_testflower",
"BifPlant_snowdrop",
"BifPlant_cactus",
"BifPlant_spare23",
"BifPlant_spare24",
"BifPlant_spare25",
"BifPlant_spare26",
"BifPlant_spare27",
"BifPlant_spare28",
"BifPlant_blackbuttercup",
"BifPlant_watercress",
"BifPlant_waterlily",
"BifPlant_bulrush",
"BifPlant_spare33",
"BifPlant_spare34",
"BifPlant_spare35",
"BifPlant_spare36",
"BifPlant_thistle",
"BifPlant_poisonivy",
"BifPlant_toadstool",
"BifPlant_venusflytrap",
"BifPlant_tumbleweed",
"BifPlant_fireweed",
"BifPlant_spare43",
"BifPlant_spare44",
"BifPlant_spare45",
"BifPlant_spare46",
"BifPlant_zzzzzz",
"Spade_aaaaaa",
"Spade",
"Spade_zzzzzz",
"SpadePart_aaaaaa",
"SpadePart_Head_aaaaaa",
"SpadePart_head1",
"SpadePart_head2",
"SpadePart_head3",
"SpadePart_head4",
"SpadePart_head5",
"SpadePart_head6",
"SpadePart_head7",
"SpadePart_head8",
"SpadePart_head9",
"SpadePart_head10",
"SpadePart_head11",
"SpadePart_head12",
"SpadePart_head13",
"SpadePart_head14",
"SpadePart_head15",
"SpadePart_head16",
"SpadePart_head17",
"SpadePart_head18",
"SpadePart_head19",
"SpadePart_head20",
"SpadePart_Head_zzzzzz",
"SpadePart_Handle_aaaaaa",
"SpadePart_handle1",
"SpadePart_handle2",
"SpadePart_handle3",
"SpadePart_handle4",
"SpadePart_handle5",
"SpadePart_handle6",
"SpadePart_handle7",
"SpadePart_handle8",
"SpadePart_handle9",
"SpadePart_handle10",
"SpadePart_handle11",
"SpadePart_handle12",
"SpadePart_handle13",
"SpadePart_handle14",
"SpadePart_handle15",
"SpadePart_handle16",
"SpadePart_handle17",
"SpadePart_handle18",
"SpadePart_handle19",
"SpadePart_handle20",
"SpadePart_Handle_zzzzzz",
"SpadePart_Extra_aaaaaa",
"SpadePart_extra1",
"SpadePart_extra2",
"SpadePart_extra3",
"SpadePart_extra4",
"SpadePart_extra5",
"SpadePart_extra6",
"SpadePart_extra7",
"SpadePart_extra8",
"SpadePart_extra9",
"SpadePart_extra10",
"SpadePart_extra11",
"SpadePart_extra12",
"SpadePart_extra13",
"SpadePart_extra14",
"SpadePart_extra15",
"SpadePart_extra16",
"SpadePart_extra17",
"SpadePart_extra18",
"SpadePart_extra19",
"SpadePart_extra20",
"SpadePart_Extra_zzzzzz",
"SpadePart_zzzzzz",
"Cursor_aaaaaa",
"Cursor_inner",
"Cursor_outer",
"Cursor_zzzzzz",
"Projectile_aaaaaa",
"Projectile_ant",
"Projectile_beetle",
"Projectile_badger",
"Projectile_bat",
"Projectile_bear",
"Projectile_beaver",
"Projectile_bee",
"Projectile_blackbutterfly",
"Projectile_bluebottle",
"Projectile_bluebutterfly",
"Projectile_boomslang",
"Projectile_brownbutterfly",
"Projectile_bushbaby",
"Projectile_buzzard",
"Projectile_spare90",
"Projectile_canary",
"Projectile_spare89",
"Projectile_cat",
"Projectile_chameleon",
"Projectile_chicken",
"Projectile_camel",
"Projectile_cow",
"Projectile_spare87",
"Projectile_crocodile",
"Projectile_crow",
"Projectile_deer",
"Projectile_spare86",
"Projectile_dog",
"Projectile_spare85",
"Projectile_dragon",
"Projectile_dragonfly",
"Projectile_duck",
"Projectile_spare84",
"Projectile_eagle",
"Projectile_spare83",
"Projectile_elephant",
"Projectile_firefly",
"Projectile_firesalamander",
"Projectile_spare81",
"Projectile_flyingpig",
"Projectile_fox",
"Projectile_frog",
"Projectile_gecko",
"Projectile_gerbil",
"Projectile_spare80",
"Projectile_spare79",
"Projectile_spare78",
"Projectile_spare76",
"Projectile_spare75",
"Projectile_goose",
"Projectile_spare74",
"Projectile_grasssnake",
"Projectile_greenbutterfly",
"Projectile_spare73",
"Projectile_spare72",
"Projectile_hedgehog",
"Projectile_hippo",
"Projectile_horse",
"Projectile_hyena",
"Projectile_hydra",
"Projectile_lemming",
"Projectile_lemmingpest",
"Projectile_spare67",
"Projectile_spare66",
"Projectile_spare65",
"Projectile_spare64",
"Projectile_lion",
"Projectile_spare63",
"Projectile_spare62",
"Projectile_spare61",
"Projectile_mandrill",
"Projectile_spare60",
"Projectile_mole",
"Projectile_spare59",
"Projectile_monkey",
"Projectile_moose",
"Projectile_moth",
"Projectile_mouse",
"Projectile_newt",
"Projectile_spare57",
"Projectile_orangebutterfly",
"Projectile_ostrich",
"Projectile_spare55",
"Projectile_spare54",
"Projectile_parrot",
"Projectile_polarbear",
"Projectile_penguin",
"Projectile_pig",
"Projectile_pigeon",
"Projectile_poisonfrog",
"Projectile_pinkbutterfly",
"Projectile_pony",
"Projectile_purplebutterfly",
"Projectile_rabbit",
"Projectile_raccoon",
"Projectile_spare50",
"Projectile_spare49",
"Projectile_redbutterfly",
"Projectile_spare48",
"Projectile_spare47",
"Projectile_robin",
"Projectile_spare45",
"Projectile_spare44",
"Projectile_salamander",
"Projectile_spare43",
"Projectile_sheep",
"Projectile_scorpion",
"Projectile_scorpionpest",
"Projectile_spare40",
"Projectile_sparrow",
"Projectile_spider",
"Projectile_squirrel",
"Projectile_spare39",
"Projectile_spare38",
"Projectile_spare37",
"Projectile_spare36",
"Projectile_swan",
"Projectile_spare35",
"Projectile_spare34",
"Projectile_spare33",
"Projectile_spare32",
"Projectile_spare31",
"Projectile_spare30",
"Projectile_unicorn",
"Projectile_batpest",
"Projectile_spare29",
"Projectile_vulture",
"Projectile_spare27",
"Projectile_whitebutterfly",
"Projectile_spare26",
"Projectile_wolf",
"Projectile_yeti",
"Projectile_worm",
"Projectile_yak",
"Projectile_yellowbutterfly",
"Projectile_zebra",
"Projectile_slugpest",
"Projectile_spare23",
"Projectile_spare22",
"Projectile_spare21",
"Projectile_spare20",
"Projectile_spare19",
"Projectile_spare18",
"Projectile_crowpest",
"Projectile_raccoonpest",
"Projectile_crocodilepest",
"Projectile_spare17",
"Projectile_molepest",
"Projectile_spare16",
"Projectile_spare15",
"Projectile_spare14",
"Projectile_spare13",
"Projectile_wolfpest",
"Projectile_mandrillpest",
"Projectile_spare12",
"Projectile_spare11",
"Projectile_snail",
"Projectile_snailpest",
"Projectile_spare3",
"Projectile_spare4",
"Projectile_spare5",
"Projectile_spare6",
"Projectile_spare7",
"Projectile_spare8",
"Projectile_spare9",
"Projectile_graysquirrel",
"Projectile_venusflytrap",
"Projectile_loather",
"Projectile_zzzzzz",
"Sweet_aaaaaa",
"Sweet_pinata",
"Sweet_super",
"Sweet_bad",
"Sweet_testdizzy",
"Sweet_testsick",
"Sweet_testangry",
"Sweet_testscared",
"Sweet_testcheered",
"Sweet_testwhacked",
"Sweet_testprice",
"Sweet_testbecomeresident",
"Sweet_testbecomenonresident",
"Sweet_testgrowup",
"Sweet_testexplode",
"Sweet_testsleep",
"Sweet_testeat",
"Sweet_testbecomeyoung",
"Sweet_happy",
"Sweet_joyous",
"Sweet_testpoison",
"Sweet_romance",
"Sweet_spare22",
"Sweet_spare23",
"Sweet_spare24",
"Sweet_spare25",
"Sweet_spare26",
"Sweet_spare27",
"Sweet_spare28",
"Sweet_spare29",
"Sweet_zzzzzz",
"Bud_aaaaaa",
"Bud_test",
"Bud_apple",
"Bud_blackberry",
"Bud_orange",
"Bud_hollybush",
"Bud_spare6",
"Bud_spare7",
"Bud_spare8",
"Bud_spare9",
"Bud_spare10",
"Bud_spare11",
"Bud_spare12",
"Bud_spare13",
"Bud_spare14",
"Bud_spare15",
"Bud_spare16",
"Bud_spare17",
"Bud_spare18",
"Bud_spare19",
"Bud_spare20",
"Bud_spare21",
"Bud_spare22",
"Bud_hazelnut",
"Bud_oak",
"Bud_fir",
"Bud_hippyapple",
"Bud_banana",
"Bud_gooseberrybush",
"Bud_gem",
"Bud_helper",
"Bud_monkeynut",
"Bud_deadlynightshade",
"Bud_zzzzzz",
"Paving_aaaaaa",
"Paving_slab",
"Paving_stone",
"Paving_block",
"Paving_crazy",
"Paving_open",
"Paving_cobble",
"Paving_decking",
"Paving_lillypad",
"Paving_hollywood",
"Paving_octagonal",
"Paving_spare_10",
"Paving_spare_11",
"Paving_spare_12",
"Paving_spare_13",
"Paving_spare_14",
"Paving_spare_15",
"Paving_spare_16",
"Paving_spare_17",
"Paving_spare_18",
"Paving_spare_19",
"Paving_spare_20",
"Paving_zzzzzz",
"HouseBlock_aaaaaa",
"HouseBlock_ant",
"HouseBlock_gym",
"HouseBlock_badger",
"HouseBlock_bat",
"HouseBlock_bear",
"HouseBlock_beaver",
"HouseBlock_bee",
"HouseBlock_beetle",
"HouseBlock_bluebottle",
"HouseBlock_butterfly",
"HouseBlock_boomslang",
"HouseBlock_beeshed",
"HouseBlock_bushbaby",
"HouseBlock_buzzard",
"HouseBlock_spare13",
"HouseBlock_canary",
"HouseBlock_spare14",
"HouseBlock_cat",
"HouseBlock_chameleon",
"HouseBlock_chicken",
"HouseBlock_spare15",
"HouseBlock_cow",
"HouseBlock_cowshed",
"HouseBlock_crocodile",
"HouseBlock_crow",
"HouseBlock_deer",
"HouseBlock_spare17",
"HouseBlock_dog",
"HouseBlock_spare18",
"HouseBlock_dragon",
"HouseBlock_dragonfly",
"HouseBlock_duck",
"HouseBlock_spare19",
"HouseBlock_eagle",
"HouseBlock_spare20",
"HouseBlock_elephant",
"HouseBlock_firefly",
"HouseBlock_firesalamander",
"HouseBlock_spare22",
"HouseBlock_flyingpig",
"HouseBlock_fox",
"HouseBlock_frog",
"HouseBlock_spare23",
"HouseBlock_spare24",
"HouseBlock_spare25",
"HouseBlock_spare26",
"HouseBlock_spare27",
"HouseBlock_spare28",
"HouseBlock_spare29",
"HouseBlock_goose",
"HouseBlock_spare30",
"HouseBlock_grasssnake",
"HouseBlock_spare11",
"HouseBlock_spare32",
"HouseBlock_spare33",
"HouseBlock_hedgehog",
"HouseBlock_hippo",
"HouseBlock_horse",
"HouseBlock_hydra",
"HouseBlock_spare35",
"HouseBlock_spare36",
"HouseBlock_spare37",
"HouseBlock_spare38",
"HouseBlock_spare39",
"HouseBlock_spare40",
"HouseBlock_spare41",
"HouseBlock_lion",
"HouseBlock_spare42",
"HouseBlock_spare43",
"HouseBlock_spare44",
"HouseBlock_mandrill",
"HouseBlock_spare45",
"HouseBlock_mole",
"HouseBlock_spare46",
"HouseBlock_monkey",
"HouseBlock_spare47",
"HouseBlock_moth",
"HouseBlock_mouse",
"HouseBlock_newt",
"HouseBlock_spare48",
"HouseBlock_spare49",
"HouseBlock_spare50",
"HouseBlock_spare51",
"HouseBlock_spare52",
"HouseBlock_parrot",
"HouseBlock_spare53",
"HouseBlock_spare54",
"HouseBlock_pig",
"HouseBlock_pigeon",
"HouseBlock_poisonfrog",
"HouseBlock_spare55",
"HouseBlock_pony",
"HouseBlock_spare86",
"HouseBlock_rabbit",
"HouseBlock_raccoon",
"HouseBlock_spare56",
"HouseBlock_spare57",
"HouseBlock_spare58",
"HouseBlock_spare59",
"HouseBlock_spare60",
"HouseBlock_spare61",
"HouseBlock_spare62",
"HouseBlock_spare63",
"HouseBlock_salamander",
"HouseBlock_spare64",
"HouseBlock_sheep",
"HouseBlock_sheepshed",
"HouseBlock_spare66",
"HouseBlock_spare67",
"HouseBlock_sparrow",
"HouseBlock_spider",
"HouseBlock_squirrel",
"HouseBlock_spare68",
"HouseBlock_spare69",
"HouseBlock_spare70",
"HouseBlock_spare71",
"HouseBlock_swan",
"HouseBlock_spare72",
"HouseBlock_spare73",
"HouseBlock_spare74",
"HouseBlock_spare75",
"HouseBlock_spare76",
"HouseBlock_spare77",
"HouseBlock_unicorn",
"HouseBlock_spare87",
"HouseBlock_spare78",
"HouseBlock_spare79",
"HouseBlock_spare80",
"HouseBlock_spare81",
"HouseBlock_spare82",
"HouseBlock_wolf",
"HouseBlock_spare83",
"HouseBlock_worm",
"HouseBlock_spare84",
"HouseBlock_spare85",
"HouseBlock_zebra",
"HouseBlock_snail",
"HouseBlock_helpermine",
"HouseBlock_animalgym",
"HouseBlock_seedos",
"HouseBlock_storkos",
"HouseBlock_dastardos",
"HouseBlock_dedos",
"HouseBlock_helperhomeone",
"HouseBlock_spare9",
"HouseBlock_spare10",
"HouseBlock_zzzzzz",
"FlowerHead_aaaaaa",
"FlowerHead_daisy",
"FlowerHead_buttercup",
"FlowerHead_bluebell",
"FlowerHead_poppy",
"FlowerHead_sunflower",
"FlowerHead_tulip",
"FlowerHead_snapdragon",
"FlowerHead_birdofparadiseplant",
"FlowerHead_orchid",
"FlowerHead_testflower",
"FlowerHead_watercress",
"FlowerHead_waterlily",
"FlowerHead_bulrush",
"FlowerHead_thistle",
"FlowerHead_poisonivy",
"FlowerHead_toadstool",
"FlowerHead_venusflytrap",
"FlowerHead_blackbuttercup",
"FlowerHead_snowdrop",
"FlowerHead_fireweed",
"FlowerHead_cactus",
"FlowerHead_spare22",
"FlowerHead_spare23",
"FlowerHead_spare24",
"FlowerHead_spare25",
"FlowerHead_spare26",
"FlowerHead_spare27",
"FlowerHead_spare28",
"FlowerHead_spare29",
"FlowerHead_zzzzzz",
"SlotMachine_aaaaaa",
"SlotMachine_generalstore",
"SlotMachine_zzzzzz",
"Vegetable_aaaaaa",
"Vegetable_carrot",
"Vegetable_turnip",
"Vegetable_spare3",
"Vegetable_pumpkin",
"Vegetable_chilli",
"Vegetable_testveg",
"Vegetable_nstestveg",
"Vegetable_maize",
"Vegetable_radish",
"Vegetable_yam",
"Vegetable_spare11",
"Vegetable_zzzzzz",
"LifeSweet_aaaaaa",
"LifeSweet_ant",
"LifeSweet_badger",
"LifeSweet_bat",
"LifeSweet_bear",
"LifeSweet_beaver",
"LifeSweet_bee",
"LifeSweet_blackbutterfly",
"LifeSweet_bluebottle",
"LifeSweet_bluebutterfly",
"LifeSweet_boomslang",
"LifeSweet_brownbutterfly",
"LifeSweet_bushbaby",
"LifeSweet_buzzard",
"LifeSweet_canary",
"LifeSweet_cat",
"LifeSweet_chameleon",
"LifeSweet_chicken",
"LifeSweet_cow",
"LifeSweet_crocodile",
"LifeSweet_crow",
"LifeSweet_deer",
"LifeSweet_dog",
"LifeSweet_dragon",
"LifeSweet_dragonfly",
"LifeSweet_duck",
"LifeSweet_eagle",
"LifeSweet_elephant",
"LifeSweet_firefly",
"LifeSweet_firesalamander",
"LifeSweet_flyingpig",
"LifeSweet_fox",
"LifeSweet_frog",
"LifeSweet_gecko",
"LifeSweet_gerbil",
"LifeSweet_goose",
"LifeSweet_grasssnake",
"LifeSweet_greenbutterfly",
"LifeSweet_hedgehog",
"LifeSweet_hippo",
"LifeSweet_horse",
"LifeSweet_hydra",
"LifeSweet_lion",
"LifeSweet_mandrill",
"LifeSweet_mole",
"LifeSweet_monkey",
"LifeSweet_moth",
"LifeSweet_mouse",
"LifeSweet_newt",
"LifeSweet_orangebutterfly",
"LifeSweet_parrot",
"LifeSweet_pig",
"LifeSweet_pigeon",
"LifeSweet_poisonfrog",
"LifeSweet_pinkbutterfly",
"LifeSweet_pony",
"LifeSweet_purplebutterfly",
"LifeSweet_rabbit",
"LifeSweet_raccoon",
"LifeSweet_redbutterfly",
"LifeSweet_salamander",
"LifeSweet_sheep",
"LifeSweet_sparrow",
"LifeSweet_spider",
"LifeSweet_squirrel",
"LifeSweet_swan",
"LifeSweet_unicorn",
"LifeSweet_batpest",
"LifeSweet_whitebutterfly",
"LifeSweet_wolf",
"LifeSweet_worm",
"LifeSweet_yellowbutterfly",
"LifeSweet_zebra",
"LifeSweet_slugpest",
"LifeSweet_crowpest",
"LifeSweet_raccoonpest",
"LifeSweet_crocodilepest",
"LifeSweet_molepest",
"LifeSweet_wolfpest",
"LifeSweet_mandrillpest",
"LifeSweet_snail",
"LifeSweet_snailpest",
"LifeSweet_graysquirrel",
"LifeSweet_zzzzzz",
"ShopKeeper_aaaaaa",
"ShopKeeper_shopkeeper",
"ShopKeeper_postman",
"ShopKeeper_doctor",
"ShopKeeper_innkeeper",
"ShopKeeper_builder",
"ShopKeeper_petshopowner",
"ShopKeeper_trader",
"ShopKeeper_tinker",
"ShopKeeper_hunter",
"ShopKeeper_spare10",
"ShopKeeper_zzzzzz",
"HomeProp_aaaaaa",
"HomeProp_defaultBed",
"HomeProp_zzzzzz",
"Fertiliser_aaaaaa",
"Fertiliser_red",
"Fertiliser_yellow",
"Fertiliser_blue",
"Fertiliser_green",
"Fertiliser_purple",
"Fertiliser_orange",
"Fertiliser_brown",
"Fertiliser_crocodiletears",
"Fertiliser_beggarsmix",
"Fertiliser_10",
"Fertiliser_11",
"Fertiliser_12",
"Fertiliser_13",
"Fertiliser_14",
"Fertiliser_15",
"Fertiliser_16",
"Fertiliser_17",
"Fertiliser_18",
"Fertiliser_19",
"Fertiliser_20",
"Fertiliser_zzzzzz",
"Contract_aaaaaa",
"Contract_waterer",
"Contract_weeder",
"Contract_groundskeeper",
"Contract_harvester",
"Contract_miner",
"Contract_groundskeepernight",
"Contract_spare7",
"Contract_spare8",
"Contract_spare9",
"Contract_spare10",
"Contract_zzzzzz",
"FertiliserPile_aaaaaa",
"FertiliserPile_red",
"FertiliserPile_yellow",
"FertiliserPile_blue",
"FertiliserPile_green",
"FertiliserPile_purple",
"FertiliserPile_orange",
"FertiliserPile_brown",
"FertiliserPile_crocodiletears",
"FertiliserPile_beggarsmix",
"FertiliserPile_10",
"FertiliserPile_11",
"FertiliserPile_12",
"FertiliserPile_13",
"FertiliserPile_14",
"FertiliserPile_15",
"FertiliserPile_16",
"FertiliserPile_17",
"FertiliserPile_18",
"FertiliserPile_19",
"FertiliserPile_20",
"FertiliserPile_zzzzzz",
"Journal_aaaaaa",
"Journal_default",
"Journal_zzzzzz",
"Accessory_aaaaaa",
"Accessory_cocoon",
"Accessory_afro",
"Accessory_backpack",
"Accessory_sharktoothnecklace",
"Accessory_sunglasses",
"Accessory_trilby",
"Accessory_deerStalker",
"Accessory_spare08",
"Accessory_oldthinmoustache",
"Accessory_oldcurlymoustache",
"Accessory_oldsmallmoustache",
"Accessory_teeth",
"Accessory_oldcolonelmoustache",
"Accessory_cowboyhat",
"Accessory_sombrero",
"Accessory_vikinghelm",
"Accessory_mohawk",
"Accessory_beaniehat",
"Accessory_blondwig",
"Accessory_minershelmet",
"Accessory_gasmask",
"Accessory_partyhorns",
"Accessory_oldhelmet",
"Accessory_bushyeyebrows",
"Accessory_oldstraightmoustache",
"Accessory_costumebathero",
"Accessory_schoolcap",
"Accessory_baseballcap",
"Accessory_oldsoldierhelmet",
"Accessory_tiara",
"Accessory_neattache",
"Accessory_collar",
"Accessory_glasses",
"Accessory_camera",
"Accessory_goldteeth",
"Accessory_bow",
"Accessory_fez",
"Accessory_rosette",
"Accessory_diamondchoker",
"Accessory_eyepatch",
"Accessory_tapshoes",
"Accessory_balletshoes",
"Accessory_crown",
"Accessory_french",
"Accessory_americanfootballhelmet",
"Accessory_armsweetbands",
"Accessory_bangle",
"Accessory_beads",
"Accessory_oldbuckteath",
"Accessory_bowtie",
"Accessory_bracelet",
"Accessory_broach",
"Accessory_bunnyear",
"Accessory_bushy",
"Accessory_chefhat",
"Accessory_colonel",
"Accessory_cowboyboots",
"Accessory_danglyearrings",
"Accessory_diamondnecklace",
"Accessory_workboots",
"Accessory_oldearingbghoop",
"Accessory_earingheart",
"Accessory_earingseashell",
"Accessory_earringsdiamond",
"Accessory_oldeyebrows",
"Accessory_fakelips",
"Accessory_falsenose",
"Accessory_falseteeth",
"Accessory_oldflowercorsage",
"Accessory_footballboots",
"Accessory_furhat",
"Accessory_glowsticknecklace",
"Accessory_pendantnecklace",
"Accessory_halo",
"Accessory_hardhat",
"Accessory_headsweetbands",
"Accessory_wellies",
"Accessory_oldkneehighboots",
"Accessory_medallion",
"Accessory_oldmohican",
"Accessory_monocle",
"Accessory_moonboots",
"Accessory_neckbolt",
"Accessory_nosering",
"Accessory_panama",
"Accessory_olddanglyearings",
"Accessory_pearlnecklace",
"Accessory_oldpedantnecklace",
"Accessory_piratehat",
"Accessory_policehat",
"Accessory_policehelm",
"Accessory_readingglasses",
"Accessory_rednose",
"Accessory_robbersmask",
"Accessory_safetygoggles",
"Accessory_santahat",
"Accessory_scarf",
"Accessory_seashellnecklace",
"Accessory_slippers",
"Accessory_snowshoe",
"Accessory_swimminggoggles",
"Accessory_thin",
"Accessory_tie",
"Accessory_tophat",
"Accessory_trainers",
"Accessory_oldchoker",
"Accessory_dastardosscarf",
"Accessory_bell",
"Accessory_bonnet",
"Accessory_beekeepershat",
"Accessory_buttercup",
"Accessory_daisy",
"Accessory_earingbghoopgold",
"Accessory_earingbghoopsilver",
"Accessory_earingspendant",
"Accessory_pearlbracelet",
"Accessory_poppy",
"Accessory_oldskigoggles",
"Accessory_sunflower",
"Accessory_trafficcone",
"Accessory_okeeyeballssprings",
"Accessory_chainnecklace",
"Accessory_chefhat2",
"Accessory_tailbow",
"Accessory_utilitybelt",
"Accessory_fruithat",
"Accessory_mrpantshat",
"Accessory_sailorhat",
"Accessory_conkerhat",
"Accessory_velawig",
"Accessory_junohelmet",
"Accessory_gruntyhat",
"Accessory_jamjarhat",
"Accessory_binnershat",
"Accessory_princesshat",
"Accessory_vonghoulhat",
"Accessory_sabremanhat",
"Accessory_orthohat",
"Accessory_knighthat",
"Accessory_headphones",
"Accessory_jiggyearrings",
"Accessory_lupusears",
"Accessory_discoshades",
"Accessory_flyinggoggles",
"Accessory_jamjarsunglasses",
"Accessory_romanticflower",
"Accessory_battletoadbracelets",
"Accessory_handcuffs",
"Accessory_sheriffbadge",
"Accessory_clockworkkey",
"Accessory_kameowings",
"Accessory_sharkfin",
"Accessory_flamencoshoes",
"Accessory_ashslippers",
"Accessory_spare155",
"Accessory_spare156",
"Accessory_spare157",
"Accessory_spare158",
"Accessory_spare159",
"Accessory_spare160",
"Accessory_spare161",
"Accessory_spare162",
"Accessory_spare163",
"Accessory_spare164",
"Accessory_spare165",
"Accessory_spare166",
"Accessory_spare167",
"Accessory_spare168",
"Accessory_spare169",
"Accessory_spare170",
"Accessory_spare171",
"Accessory_spare172",
"Accessory_spare173",
"Accessory_spare174",
"Accessory_spare175",
"Accessory_spare176",
"Accessory_spare177",
"Accessory_spare178",
"Accessory_spare179",
"Accessory_spare180",
"Accessory_spare181",
"Accessory_spare182",
"Accessory_spare183",
"Accessory_spare184",
"Accessory_spare185",
"Accessory_spare186",
"Accessory_spare187",
"Accessory_spare188",
"Accessory_spare189",
"Accessory_spare190",
"Accessory_spare191",
"Accessory_spare192",
"Accessory_spare193",
"Accessory_spare194",
"Accessory_spare195",
"Accessory_spare196",
"Accessory_spare197",
"Accessory_spare198",
"Accessory_spare199",
"Accessory_spare200",
"Accessory_spare201",
"Accessory_spare202",
"Accessory_spare203",
"Accessory_spare204",
"Accessory_spare205",
"Accessory_spare206",
"Accessory_spare207",
"Accessory_spare208",
"Accessory_spare209",
"Accessory_spare210",
"Accessory_spare211",
"Accessory_spare212",
"Accessory_spare213",
"Accessory_spare214",
"Accessory_spare215",
"Accessory_spare216",
"Accessory_spare217",
"Accessory_spare218",
"Accessory_spare219",
"Accessory_spare220",
"Accessory_spare221",
"Accessory_spare222",
"Accessory_spare223",
"Accessory_spare224",
"Accessory_spare225",
"Accessory_spare226",
"Accessory_spare227",
"Accessory_spare228",
"Accessory_spare229",
"Accessory_spare230",
"Accessory_spare231",
"Accessory_spare232",
"Accessory_spare233",
"Accessory_spare234",
"Accessory_spare235",
"Accessory_spare236",
"Accessory_spare237",
"Accessory_spare238",
"Accessory_spare239",
"Accessory_spare240",
"Accessory_spare241",
"Accessory_spare242",
"Accessory_spare243",
"Accessory_spare244",
"Accessory_zzzzzz"

};


inline static std::vector<PinataIDs> g_PinataIDs = {
    {3, "Raisant", ActorType::Pinata, Accessibility::InGame},
    {5, "Badgesicle", ActorType::Pinata, Accessibility::InGame},
    {6, "Sherbat", ActorType::Pinata, Accessibility::InGame},
    {7, "Fizzlybear", ActorType::Pinata, Accessibility::InGame},
    {8, "Sweetooth", ActorType::Pinata, Accessibility::InGame},
    {9, "Buzzlegum", ActorType::Pinata, Accessibility::InGame},
    {10, "Black Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {11, "Taffly", ActorType::Pinata, Accessibility::InGame},
    {12, "Blue Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {13, "Twingersnap", ActorType::Pinata, Accessibility::InGame},
    {14, "Brown Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {15, "Galagoogoo", ActorType::Pinata, Accessibility::InGame},
    {16, "Buzzenge", ActorType::Pinata, Accessibility::InGame},
    {18, "Candary", ActorType::Pinata, Accessibility::InGame},
    {20, "Kittyfloss", ActorType::Pinata, Accessibility::InGame},
    {21, "Jameleon", ActorType::Pinata, Accessibility::InGame},
    {22, "Cluckles", ActorType::Pinata, Accessibility::InGame},
    {24, "Moozipan", ActorType::Pinata, Accessibility::InGame},
    {26, "Cocoadile", ActorType::Pinata, Accessibility::InGame},
    {27, "Crowla", ActorType::Pinata, Accessibility::InGame},
    {28, "Doenut", ActorType::Pinata, Accessibility::InGame},
    {30, "Barkbark", ActorType::Pinata, Accessibility::InGame},
    {32, "Dragonache", ActorType::Pinata, Accessibility::InGame},
    {33, "Dragumfly", ActorType::Pinata, Accessibility::InGame},
    {34, "Quackberry", ActorType::Pinata, Accessibility::InGame},
    {36, "Eaglair", ActorType::Pinata, Accessibility::InGame},
    {38, "Elephanilla", ActorType::Pinata, Accessibility::InGame},
    {39, "Reddhott", ActorType::Pinata, Accessibility::InGame},
    {40, "Salamango", ActorType::Pinata, Accessibility::InGame},
    {42, "Pigxie", ActorType::Pinata, Accessibility::InGame},
    {43, "Pretztail", ActorType::Pinata, Accessibility::InGame},
    {44, "Lickatoad", ActorType::Pinata, Accessibility::InGame},
    {52, "Juicygoose", ActorType::Pinata, Accessibility::InGame},
    {54, "Syrupent", ActorType::Pinata, Accessibility::InGame},
    {55, "Green Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {58, "Fudgehog", ActorType::Pinata, Accessibility::InGame},
    {59, "Chippopotamus", ActorType::Pinata, Accessibility::InGame},
    {60, "Horstachio", ActorType::Pinata, Accessibility::InGame},
    {62, "Fourheads", ActorType::Pinata, Accessibility::InGame},
    {63, "Lemmoning", ActorType::Pinata, Accessibility::Cut},
    {64, "Sour Lemmoning", ActorType::Pinata, Accessibility::Cut},
    {69, "Roario", ActorType::Pinata, Accessibility::InGame},
    {73, "Bonboon", ActorType::Pinata, Accessibility::InGame},
    {75, "Profitamole", ActorType::Pinata, Accessibility::InGame},
    {77, "Cinnamonkey", ActorType::Pinata, Accessibility::InGame},
    {78, "Moojo", ActorType::Pinata, Accessibility::Cut},
    {79, "Mothdrop", ActorType::Pinata, Accessibility::InGame},
    {80, "Mousemallow", ActorType::Pinata, Accessibility::InGame},
    {81, "Newtgat", ActorType::Pinata, Accessibility::InGame},
    {83, "Orange Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {87, "Parrybo", ActorType::Pinata, Accessibility::InGame},
    {88, "Polollybear", ActorType::Pinata, Accessibility::Cut},
    {89, "Pengum", ActorType::Pinata, Accessibility::Cut},
    {90, "Rashberry", ActorType::Pinata, Accessibility::InGame},
    {91, "Pudgeon", ActorType::Pinata, Accessibility::InGame},
    {92, "Lackatoad", ActorType::Pinata, Accessibility::InGame},
    {93, "Pink Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {94, "Ponocky", ActorType::Pinata, Accessibility::InGame},
    {95, "Purple Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {96, "Bunnycomb", ActorType::Pinata, Accessibility::InGame},
    {97, "Macaraccoon", ActorType::Pinata, Accessibility::InGame},
    {100, "Red Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {103, "Robean", ActorType::Pinata, Accessibility::Cut},
    {108, "Goobaa", ActorType::Pinata, Accessibility::InGame},
    {112, "Sparrowmint", ActorType::Pinata, Accessibility::InGame},
    {113, "Arocknid", ActorType::Pinata, Accessibility::InGame},
    {114, "Squazzil", ActorType::Pinata, Accessibility::InGame},
    {119, "Swanana", ActorType::Pinata, Accessibility::InGame},
    {126, "Chewnicorn", ActorType::Pinata, Accessibility::InGame},
    {127, "Sour Sherbat", ActorType::Pinata, Accessibility::InGame},
    {131, "White Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {133, "Mallowolf", ActorType::Pinata, Accessibility::InGame},
    {134, "Jeli", ActorType::Pinata, Accessibility::Cut},
    {135, "Whirlm", ActorType::Pinata, Accessibility::InGame},
    {136, "Flapjak", ActorType::Pinata, Accessibility::Cut},
    {137, "Yellow Flutterscotch", ActorType::Pinata, Accessibility::InGame},
    {138, "Zumbug", ActorType::Pinata, Accessibility::InGame},
    {146, "Sour Crowla", ActorType::Pinata, Accessibility::InGame},
    {147, "Sour Macaraccoon", ActorType::Pinata, Accessibility::InGame},
    {148, "Sour Cocoadile", ActorType::Pinata, Accessibility::InGame},
    {150, "Sour Profitamole", ActorType::Pinata, Accessibility::InGame},
    {155, "Sour Mallowolf", ActorType::Pinata, Accessibility::InGame},
    {156, "Sour Bonboon", ActorType::Pinata, Accessibility::InGame},
    {159, "Shellybean", ActorType::Pinata, Accessibility::InGame},
    {160, "Sour Shellybean", ActorType::Pinata, Accessibility::InGame},
    {171, "Crate1", ActorType::Crate, Accessibility::InGame},
    {172, "Crate (Xbox Live)"},
    {173, "Crate3", ActorType::Crate, Accessibility::InGame},
    {184, "Raisant Egg", ActorType::Egg, Accessibility::InGame},
    {186, "Egg2", ActorType::Egg, Accessibility::InGame},
    {187, "Egg3", ActorType::Egg, Accessibility::InGame},
    {188, "Egg4", ActorType::Egg, Accessibility::InGame},
    {189, "Egg5", ActorType::Egg, Accessibility::InGame},
    {192, "Egg6", ActorType::Egg, Accessibility::InGame},
    {194, "Egg7", ActorType::Egg, Accessibility::InGame},
    {195, "Egg8", ActorType::Egg, Accessibility::InGame},
    {196, "Egg9", ActorType::Egg, Accessibility::InGame},
    {198, "Egg10", ActorType::Egg, Accessibility::InGame},
    {200, "Egg11", ActorType::Egg, Accessibility::InGame},
    {201, "Egg12", ActorType::Egg, Accessibility::InGame},
    {202, "Egg13", ActorType::Egg, Accessibility::InGame },
    {205, "Egg14", ActorType::Egg, Accessibility::InGame },
    {206, "Egg15", ActorType::Egg, Accessibility::InGame },
    {207, "Egg16", ActorType::Egg, Accessibility::InGame },
    {209, "Egg17", ActorType::Egg, Accessibility::InGame },
    {211, "Egg18", ActorType::Egg, Accessibility::InGame },
    {212, "Egg19", ActorType::Egg, Accessibility::InGame },
    {213, "Egg20", ActorType::Egg, Accessibility::InGame },
    {215, "Egg21", ActorType::Egg, Accessibility::InGame },
    {217, "Egg22", ActorType::Egg, Accessibility::InGame },
    {218, "Egg23", ActorType::Egg, Accessibility::InGame },
    {219, "Egg24", ActorType::Egg, Accessibility::InGame },
    {221, "Egg25", ActorType::Egg, Accessibility::InGame },
    {222, "Egg26", ActorType::Egg, Accessibility::InGame },
    {223, "Egg27", ActorType::Egg, Accessibility::InGame },
    {231, "Egg28", ActorType::Egg, Accessibility::InGame },
    {233, "Egg29", ActorType::Egg, Accessibility::InGame },
    {237, "Egg30", ActorType::Egg, Accessibility::InGame },
    {238, "Egg31", ActorType::Egg, Accessibility::InGame },
    {239, "Egg32", ActorType::Egg, Accessibility::InGame },
    {240, "Egg33", ActorType::Egg, Accessibility::InGame },
    {248, "Egg34", ActorType::Egg, Accessibility::InGame },
    {252, "Egg35", ActorType::Egg, Accessibility::InGame },
    {254, "Egg36", ActorType::Egg, Accessibility::InGame },
    {256, "Egg37", ActorType::Egg, Accessibility::InGame },
    {258, "Egg38", ActorType::Egg, Accessibility::InGame },
    {259, "Egg39", ActorType::Egg, Accessibility::InGame },
    {260, "Egg40", ActorType::Egg, Accessibility::InGame },
    {266, "Egg41", ActorType::Egg, Accessibility::InGame },
    {269, "Egg42", ActorType::Egg, Accessibility::InGame },
    {270, "Egg43", ActorType::Egg, Accessibility::InGame },
    {271, "Egg44", ActorType::Egg, Accessibility::InGame },
    {273, "Egg45", ActorType::Egg, Accessibility::InGame },
    {275, "Egg46", ActorType::Egg, Accessibility::InGame },
    {276, "Egg47", ActorType::Egg, Accessibility::InGame },
    {279, "Egg48", ActorType::Egg, Accessibility::InGame },
    {287, "Egg49", ActorType::Egg, Accessibility::InGame },
    {291, "Egg50", ActorType::Egg, Accessibility::InGame },
    {292, "Egg51", ActorType::Egg, Accessibility::InGame },
    {293, "Egg52", ActorType::Egg, Accessibility::InGame },
    {298, "Egg53", ActorType::Egg, Accessibility::InGame },
    {306, "Egg54", ActorType::Egg, Accessibility::InGame },
    {307, "Cutscene Egg (Sour Sherbat)", ActorType::Egg, Accessibility::UnobtainableInGame },
    {311, "Egg55", ActorType::Egg, Accessibility::InGame },
    {312, "Egg56", ActorType::Egg, Accessibility::InGame },
    {314, "Egg57", ActorType::Egg, Accessibility::InGame },
    {317, "Egg58", ActorType::Egg, Accessibility::InGame },
    {319, "Egg59", ActorType::Egg, Accessibility::InGame },
    {320, "Shellybean Egg", ActorType::Egg, Accessibility::InGame},
    {332, "Acorn", ActorType::Fruit, Accessibility::InGame },
    {333, "Apple", ActorType::Fruit, Accessibility::InGame },
    {334, "Banana", ActorType::Fruit, Accessibility::InGame },
    {337, "Nightshade Berry", ActorType::Fruit, Accessibility::InGame },
    {338, "Fir Cone", ActorType::Fruit, Accessibility::InGame },
    {339, "Gem1", ActorType::Fruit, Accessibility::InGame },
    {340, "Hazelnut", ActorType::Fruit, Accessibility::InGame },
    {342, "Monkeynut", ActorType::Fruit, Accessibility::InGame },
    {346, "Blackberry", ActorType::Fruit, Accessibility::InGame },
    {347, "Gooseberry", ActorType::Fruit, Accessibility::InGame },
    {350, "Gem2", ActorType::Fruit, Accessibility::InGame },
    {351, "Gem3", ActorType::Fruit, Accessibility::InGame },
    {352, "Gem4", ActorType::Fruit, Accessibility::InGame },
    {353, "Gem5", ActorType::Fruit, Accessibility::InGame },
    {354, "Gem6", ActorType::Fruit, Accessibility::InGame },
    {361, "Weedling", ActorType::Helper, Accessibility::InGame },
    {362, "Leafos", ActorType::Helper, Accessibility::InGame },
    {363, "Ivor Bargain", ActorType::Shopkeeper, Accessibility::InGame },
    {364, "Storkos", ActorType::Helper, Accessibility::InGame },
    {365, "Sprinkling", ActorType::Helper, Accessibility::InGame },
    {366, "Seedos", ActorType::Helper, Accessibility::InGame },
    {367, "Bart", ActorType::Shopkeeper, Accessibility::InGame },
    {368, "Diggerling", ActorType::Helper, Accessibility::InGame },
    {369, "Ruffian1", ActorType::Ruffian, Accessibility::InGame },
    {370, "Ruffian2", ActorType::Ruffian, Accessibility::InGame },
    {371, "Ruffian3", ActorType::Ruffian, Accessibility::InGame },
    {372, "Ruffian4", ActorType::Ruffian, Accessibility::InGame },
    {373, "Doc Patchingo", ActorType::Shopkeeper, Accessibility::InGame },
    {376, "Gatherling", ActorType::Helper, Accessibility::InGame },
    {377, "Watchling1", ActorType::Helper, Accessibility::InGame },
    {378, "Night Watchling", ActorType::Helper, Accessibility::InGame },
    {380, "Willy", ActorType::Shopkeeper, Accessibility::InGame },
    {381, "Dastardos", ActorType::Helper, Accessibility::InGame },
    {382, "Professor Pester", ActorType::Ruffian, Accessibility::InGame },
    {399, "Carrot Seed", ActorType::Seed, Accessibility::InGame },
    {400, "Turnip Seed", ActorType::Seed, Accessibility::InGame },
    {402, "Pumpkin Seed", ActorType::Seed, Accessibility::InGame },
    {403, "Chili Seed", ActorType::Seed, Accessibility::InGame },
    {404, "Cutscene Seed (Carrot)", ActorType::Seed, Accessibility::UnobtainableInGame },
    {406, "Corn Seed", ActorType::Seed, Accessibility::InGame },
    {409, "Daisy Seed", ActorType::Seed, Accessibility::InGame },
    {410, "Buttercup Seed", ActorType::Seed, Accessibility::InGame },
    {411, "Bluebell Seed", ActorType::Seed, Accessibility::InGame },
    {412, "Poppy Seed", ActorType::Seed, Accessibility::InGame },
    {413, "Sunflower Seed", ActorType::Seed, Accessibility::InGame },
    {414, "Tulip Seed", ActorType::Seed, Accessibility::InGame },
    {415, "Snapdragon Seed", ActorType::Seed, Accessibility::InGame },
    {416, "Bird of Paradise", ActorType::Seed, Accessibility::InGame },
    {417, "Orchid Seed", ActorType::Seed, Accessibility::InGame },
    {428, "Watercress Seed", ActorType::Seed, Accessibility::InGame },
    {429, "Water Lily Seed", ActorType::Seed, Accessibility::InGame },
    {430, "Bullrush Seed", ActorType::Seed, Accessibility::InGame },
    {435, "Thistle Seed", ActorType::Seed, Accessibility::InGame },
    {436, "Poison Ivy Seed", ActorType::Seed, Accessibility::InGame },
    {437, "Toadstool Seed", ActorType::Seed, Accessibility::InGame },
    {438, "Venus Pinata Trap", ActorType::Seed, Accessibility::InGame },
    {446, "Apple Seed", ActorType::Seed, Accessibility::InGame },
    {447, "Hazelnut Seed", ActorType::Seed, Accessibility::InGame },
    {448, "Oak Seed", ActorType::Seed, Accessibility::InGame },
    {449, "Fir Seed", ActorType::Seed, Accessibility::InGame },
    {450, "Blackberry Seed", ActorType::Seed, Accessibility::InGame },
    {451, "Banana Seed", ActorType::Seed, Accessibility::InGame },
    {452, "Gooseberry Seed", ActorType::Seed, Accessibility::InGame },
    {453, "Gem Seed", ActorType::Seed, Accessibility::InGame },
    {455, "Monkeynut Seed", ActorType::Seed, Accessibility::InGame },
    {456, "Nightshade Seed", ActorType::Seed, Accessibility::InGame },
    {470, "Raisant Home", ActorType::Home, Accessibility::InGame },
    {472, "Badgesicle Home", ActorType::Home, Accessibility::InGame },
    {473, "Sherbat Home", ActorType::Home, Accessibility::InGame },
    {474, "Fizzlybear Home", ActorType::Home, Accessibility::InGame },
    {475, "Sweetooth Home", ActorType::Home, Accessibility::InGame },
    {476, "Buzzlegum Home", ActorType::Home, Accessibility::InGame },
    {478, "Taffly Home", ActorType::Home, Accessibility::InGame },
    {479, "Flutterscotch Home", ActorType::Home, Accessibility::InGame },
    {480, "Twingersnap Home", ActorType::Home, Accessibility::InGame },
    {481, "Honey hive", ActorType::Home, Accessibility::InGame },
    {482, "Galagoogoo Home", ActorType::Home, Accessibility::InGame },
    {483, "Buzzenge Home", ActorType::Home, Accessibility::InGame },
    {485, "Candary Home", ActorType::Home, Accessibility::InGame },
    {487, "Kittyfloss Home", ActorType::Home, Accessibility::InGame },
    {488, "Jameleon Home", ActorType::Home, Accessibility::InGame },
    {489, "Cluckles Home", ActorType::Home, Accessibility::InGame },
    {491, "Moozipan Home", ActorType::Home, Accessibility::InGame },
    {492, "Milking Shed", ActorType::SpecialBuilding, Accessibility::InGame },
    {493, "Cocoadile Home", ActorType::Home, Accessibility::InGame },
    {494, "Crowla Home", ActorType::Home, Accessibility::InGame },
    {495, "Doenut Home", ActorType::Home, Accessibility::InGame },
    {497, "Barkbark Home", ActorType::Home, Accessibility::InGame },
    {500, "Dragumfly Home", ActorType::Home, Accessibility::InGame },
    {501, "Quackberry Home", ActorType::Home, Accessibility::InGame },
    {503, "Eaglair Home", ActorType::Home, Accessibility::InGame },
    {505, "Elephanilla Home", ActorType::Home, Accessibility::InGame },
    {506, "Reddhott Home", ActorType::Home, Accessibility::InGame },
    {507, "Salamango Home", ActorType::Home, Accessibility::InGame },
    {509, "Mystery Home", ActorType::Home, Accessibility::InGame },
    {510, "Pretztail Home", ActorType::Home, Accessibility::InGame },
    {511, "Lickatoad Home", ActorType::Home, Accessibility::InGame },
    {519, "Juicygoose Home", ActorType::Home, Accessibility::InGame },
    {521, "Syrupent home", ActorType::Home, Accessibility::InGame },
    {525, "Fudgehog Home", ActorType::Home, Accessibility::InGame },
    {526, "Chippopotamus Home", ActorType::Home, Accessibility::InGame },
    {527, "Horstachio Home", ActorType::Home, Accessibility::InGame },
    {528, "Fourheads Home", ActorType::Home, Accessibility::InGame },
    {536, "Roario Home", ActorType::Home, Accessibility::InGame },
    {540, "Bonboon Home", ActorType::Home, Accessibility::InGame },
    {542, "Profitamole Home", ActorType::Home, Accessibility::InGame },
    {544, "Cinnamonkey Home", ActorType::Home, Accessibility::InGame },
    {546, "Mothdrop Home", ActorType::Home, Accessibility::InGame },
    {547, "Mousemallow Home", ActorType::Home, Accessibility::InGame },
    {548, "Newtgat Home", ActorType::Home, Accessibility::InGame },
    {554, "Parrybo Home", ActorType::Home, Accessibility::InGame },
    {557, "Rashberry Home", ActorType::Home, Accessibility::InGame },
    {558, "Pudgeon Home", ActorType::Home, Accessibility::InGame },
    {559, "Lackatoad Home", ActorType::Home, Accessibility::InGame },
    {561, "Ponocky Home", ActorType::Home, Accessibility::InGame },
    {563, "Bunnycomb Home", ActorType::Home, Accessibility::InGame },
    {564, "Macaraccoon Home", ActorType::Home, Accessibility::InGame },
    {575, "Goobaa Home", ActorType::Home, Accessibility::InGame },
    {576, "Shearing Shed", ActorType::Home, Accessibility::InGame },
    {579, "Sparrowmint Home", ActorType::Home, Accessibility::InGame },
    {580, "Arocknid Home", ActorType::Home, Accessibility::InGame },
    {581, "Squazzil Home", ActorType::Home, Accessibility::InGame },
    {586, "Swanana Home", ActorType::Home, Accessibility::InGame },
    {593, "Chewnicorn Home", ActorType::Home, Accessibility::InGame },
    {600, "Mallowolf Home", ActorType::Home, Accessibility::InGame },
    {602, "Whirlm Home", ActorType::Home, Accessibility::InGame },
    {605, "Zumbug Home", ActorType::Home, Accessibility::InGame },
    {606, "Shellybean Home", ActorType::Home, Accessibility::InGame },
    {607, "Mine", ActorType::SpecialBuilding, Accessibility::InGame },
    {613, "Helper Home", ActorType::SpecialBuilding, Accessibility::InGame },
    {618, "Soil", ActorType::LandType, Accessibility::InGame },
    {619, "Sand", ActorType::LandType, Accessibility::UnobtainableInGame },
    {620, "Snow", ActorType::LandType, Accessibility::UnobtainableInGame },
    {621, "Grass", ActorType::LandType, Accessibility::InGame },
    {622, "Mud", ActorType::LandType, Accessibility::InGame },
    {623, "Long Grass", ActorType::LandType, Accessibility::InGame },
    {624, "NULL1", ActorType::Unknown, Accessibility::UnobtainableInGame },
    {625, "NULL2", ActorType::Unknown, Accessibility::UnobtainableInGame },
    {626, "NULL3", ActorType::Unknown, Accessibility::UnobtainableInGame },
    {627, "Extra Garden Space", ActorType::LandType, Accessibility::InGame },
    {628, "Shallow Water", ActorType::LandType, Accessibility::InGame },
    {629, "Deep Water", ActorType::LandType, Accessibility::InGame },
    {630, "NULL4", ActorType::Unknown, Accessibility::UnobtainableInGame },
    {631, "Hard Soil", ActorType::LandType, Accessibility::InGame },
    {634, "Honey", ActorType::Produse, Accessibility::InGame },
    {635, "Milk", ActorType::Produse, Accessibility::InGame },
    {636, "Wool", ActorType::Produse, Accessibility::InGame },
    {640, "Rainbow Gem", ActorType::Produse, Accessibility::InGame },
    {644, "Cheese", ActorType::Produse, Accessibility::InGame },
    {645, "Bread", ActorType::Produse, Accessibility::InGame },
    {646, "Jack o' Lantern", ActorType::Produse, Accessibility::InGame },
    {647, "Jam", ActorType::Produse, Accessibility::InGame },
    {648, "Medicine", ActorType::Produse, Accessibility::InGame },
    {649, "Mushroom", ActorType::Produse, Accessibility::InGame },
    {650, "Sandwich", ActorType::Produse, Accessibility::InGame },
    {651, "Sapphire", ActorType::Produse, Accessibility::InGame },
    {652, "Diamond", ActorType::Produse, Accessibility::InGame },
    {653, "Mine Workings", ActorType::Produse, Accessibility::InGame },
    {654, "Gold Nugget", ActorType::Produse, Accessibility::InGame },
    {655, "Gold Flake", ActorType::Produse, Accessibility::InGame },
    {656, "Gooseberry Fool", ActorType::Produse, Accessibility::InGame },
    {657, "Peanut butter", ActorType::Produse, Accessibility::InGame },
    {658, "Banana Split", ActorType::Produse, Accessibility::InGame },
    {659, "Bone", ActorType::Produse, Accessibility::InGame },
    {660, "Carrot Cake", ActorType::Produse, Accessibility::InGame },
    {661, "Toffee Apple", ActorType::Produse, Accessibility::InGame },
    {662, "Emerald", ActorType::Produse, Accessibility::InGame },
    {665, "Firebrand", ActorType::Decor, Accessibility::InGame },
    {666, "Pirate Statue", ActorType::Decor, Accessibility::InGame },
    {671, "Bird and Bear Statue", ActorType::Decor, Accessibility::InGame },
    {674, "Birdbath", ActorType::Decor, Accessibility::InGame },
    {677, "Ornamental Stones", ActorType::Decor, Accessibility::InGame },
    {678, "Surfboard", ActorType::Decor, Accessibility::InGame },
    {679, "Windchime Mk1", ActorType::Decor, Accessibility::InGame },
    {680, "Hay Bale", ActorType::Decor, Accessibility::InGame },
    {681, "Milk Churn", ActorType::Decor, Accessibility::InGame },
    {684, "Fish Fountain", ActorType::Decor, Accessibility::InGame },
    {685, "Swan Fountain", ActorType::Decor, Accessibility::InGame },
    {686, "Glow Rocks", ActorType::Decor, Accessibility::InGame },
    {688, "Pile of Leaves", ActorType::Decor, Accessibility::InGame },
    {690, "Barrel", ActorType::Decor, Accessibility::InGame },
    {692, "Captains Cutlass", ActorType::Decor, Accessibility::InGame },
    {693, "Flower Carving", ActorType::Decor, Accessibility::InGame },
    {694, "Cartwheel", ActorType::Decor, Accessibility::InGame },
    {699, "Moon-on-a-Stick", ActorType::Decor, Accessibility::InGame },
    {700, "Tombstone", ActorType::Decor, Accessibility::InGame },
    {701, "Water Waiver", ActorType::Decor, Accessibility::InGame },
    {703, "Toxic Drum", ActorType::Decor, Accessibility::InGame },
    {704, "Sundial", ActorType::Decor, Accessibility::InGame },
    {707, "Lantern O' Loot", ActorType::Decor, Accessibility::InGame },
    {744, "Old Fence", ActorType::Decor, Accessibility::InGame },
    {745, "Ruined Building", ActorType::Decor, Accessibility::InGame },
    {746, "Building Remains", ActorType::Decor, Accessibility::InGame },
    {747, "Rock", ActorType::Decor, Accessibility::InGame },
    {748, "Broken Statue", ActorType::Decor, Accessibility::InGame },
    {749, "Tree Stump", ActorType::Decor, Accessibility::UnobtainableInGame },
    {750, "Rotten Tree", ActorType::Decor, Accessibility::InGame },
    {751, "Old Stump", ActorType::Decor, Accessibility::InGame },
    {752, "Wheel", ActorType::Decor, Accessibility::InGame },
    {755, "Dastardos Scarer", ActorType::Decor, Accessibility::InGame },
    {756, "Fir Tree Log", ActorType::Decor, Accessibility::InGame },
    {757, "Red Eye Rainbow", ActorType::Decor, Accessibility::InGame },
    {758, "Hollow Log", ActorType::Decor, Accessibility::UnobtainableInGame },
    {759, "Junk Drum", ActorType::Decor, Accessibility::UnobtainableInGame },
    {760, "Junk Skip", ActorType::Decor, Accessibility::UnobtainableInGame },
    {761, "Junk Coop", ActorType::Decor, Accessibility::UnobtainableInGame },
    {762, "Junk Pan", ActorType::Decor, Accessibility::UnobtainableInGame },
    {763, "Junk Tank", ActorType::Decor, Accessibility::UnobtainableInGame },
    {764, "Ruined Building", ActorType::Decor, Accessibility::UnobtainableInGame },
    {765, "Jar 'o' Light", ActorType::Decor, Accessibility::InGame },
    {766, "Oil Lamp", ActorType::Decor, Accessibility::InGame },
    {767, "Vase", ActorType::Decor, Accessibility::InGame },
    {768, "Wind Chime Mk2", ActorType::Decor, Accessibility::InGame },
    {769, "Sword Mk2", ActorType::Decor, Accessibility::InGame },
    {770, "Old Arcade Machine", ActorType::Decor, Accessibility::UnobtainableInGame },
    {793, "Title (Japan)", ActorType::Decor, Accessibility::UnobtainableInGame },
    {794, "Tower of Sour Base", ActorType::Totem, Accessibility::UnobtainableInGame },
    {795, "Sherbat Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {796, "Cocoadile Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {797, "Crowla Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {798, "Bonboon Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {799, "Profitamole Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {800, "Macaraccoon Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {801, "Shellybean Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {802, "Mallowolf Block", ActorType::Totem, Accessibility::UnobtainableInGame },
    {803, "Title (English)", ActorType::Decor, Accessibility::UnobtainableInGame },
    {806, "Rusty Watering Can", ActorType::Tool, Accessibility::InGame },
    {807, "Tin Watering Can", ActorType::Tool, Accessibility::InGame },
    {808, "Gold Watering Can", ActorType::Tool, Accessibility::InGame },
    {809, "Glass Watering Can", ActorType::Tool, Accessibility::InGame },
    {810, "Everpour 5000 Watering Can", ActorType::Tool, Accessibility::InGame },
    {811, "One Pour Wonder", ActorType::Tool, Accessibility::InGame },
    {828, "Grass Packet", ActorType::Tool, Accessibility::InGame },
    {829, "Long Grass Packet", ActorType::Tool, Accessibility::InGame },
    {830, "Sand Packet", ActorType::Tool, Accessibility::Cut },
    {831, "Snow Packet", ActorType::Tool, Accessibility::Cut },
    {850, "Wooden Fence", ActorType::Fence, Accessibility::InGame },
    {851, "Wooden Gate", ActorType::Fence, Accessibility::InGame },
    {852, "Hedge", ActorType::Fence, Accessibility::InGame },
    {854, "Stone Wall", ActorType::Fence, Accessibility::InGame },
    {855, "Iron Gate", ActorType::Fence, Accessibility::InGame },
    {856, "Oak Gate", ActorType::Fence, Accessibility::InGame },
    {857, "Wooden Picket Fence", ActorType::Fence, Accessibility::InGame },
    {858, "Wire Fence", ActorType::Fence, Accessibility::InGame },
    {859, "Iron Railings", ActorType::Fence, Accessibility::InGame },
    {864, "Bronze Chocolate Coin", ActorType::Coin, Accessibility::InGame },
    {865, "Silver Chocolate Coin", ActorType::Coin, Accessibility::InGame },
    {866, "Gold Chocolate Coin", ActorType::Coin, Accessibility::InGame },
    {867, "Big Gold Chocolate Coin", ActorType::Coin, Accessibility::InGame },
    {877, "Apple Tree1", ActorType::Tree, Accessibility::InGame },
    {878, "Apple Tree (Tiny)", ActorType::Tree, Accessibility::Cut },
    {879, "Hazel Tree", ActorType::Tree, Accessibility::InGame },
    {880, "Oak Tree", ActorType::Tree, Accessibility::InGame },
    {881, "Fir Tree", ActorType::Tree, Accessibility::InGame },
    {882, "Blackberry bush", ActorType::Tree, Accessibility::InGame },
    {883, "Banana Tree", ActorType::Tree, Accessibility::InGame },
    {884, "Gooseberry bush", ActorType::Tree, Accessibility::InGame },
    {885, "Gem Tree", ActorType::Tree, Accessibility::InGame },
    {887, "Monkeynut Tree", ActorType::Tree, Accessibility::InGame },
    {888, "Nightshade bush", ActorType::Tree, Accessibility::InGame },
   // {890, "Nightshade bush2", ActorType::Tree, Accessibility::InGame }, //Crashes
    {925, "Carrot Plant", ActorType::Flower, Accessibility::InGame },
    {926, "Turnip Plant", ActorType::Flower, Accessibility::InGame },
    {928, "Pumpkin Plant", ActorType::Flower, Accessibility::InGame },
    {929, "Chili Plant", ActorType::Flower, Accessibility::InGame },
    {932, "Corn Plant", ActorType::Flower, Accessibility::InGame },
    {933, "Orchids1 Plant", ActorType::Flower, Accessibility::InGame },
    {935, "Daisy Plant", ActorType::Flower, Accessibility::InGame },
    {936, "Buttercup Plant", ActorType::Flower, Accessibility::InGame },
    {937, "Bluebell Plant", ActorType::Flower, Accessibility::InGame },
    {938, "Poppy Plant", ActorType::Flower, Accessibility::InGame },
    {939, "Sunflower Plant", ActorType::Flower, Accessibility::InGame },
    {940, "Tulip Plant", ActorType::Flower, Accessibility::InGame },
	{ 941, "Snapdragon Plant", ActorType::Flower, Accessibility::InGame },
    {942, "Bird of Paradise Plant", ActorType::Flower, Accessibility::InGame},
    {943, "Orchids2 Plant", ActorType::Flower, Accessibility::InGame},
    //{945, "Orchids3 Plant", ActorType::Flower, Accessibility::InGame}, //Crashes
    {954, "Watercress Plant", ActorType::Flower, Accessibility::InGame},
    {955, "Water Lily Plant", ActorType::Flower, Accessibility::InGame},
    {956, "Bullrush Plant", ActorType::Flower, Accessibility::InGame},
    {961, "Thistle Plant", ActorType::Weed, Accessibility::InGame },
    {962, "Poison Ivy Plant", ActorType::Weed, Accessibility::InGame },
    {963, "Toadstool Plant", ActorType::Weed, Accessibility::InGame },
    {964, "Venus Pinata Trap Plant", ActorType::Weed, Accessibility::InGame },
    {966, "Orchids4 Plant", ActorType::Flower, Accessibility::InGame },
    {977, "Freebie Shovel Head", ActorType::Tool, Accessibility::InGame },
    {978, "Seed Shovel Head", ActorType::Tool, Accessibility::InGame },
    {979, "Pond Shovel Head", ActorType::Tool, Accessibility::InGame },
    {980, "Treecutter Shovel Head", ActorType::Tool, Accessibility::InGame },
    {981, "Dastardos Head", ActorType::Tool, Accessibility::InGame },
    {999, "Freebie Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1000, "Iron Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1001, "Bronze Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1002, "Silver Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1003, "Gold Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1004, "Platinum Shovel Handle", ActorType::Tool, Accessibility::InGame },
    {1021, "Chocolate Sniffer", ActorType::Tool, Accessibility::InGame },
    {1218, "Pinata Candy", ActorType::Candy, Accessibility::InGame },
    {1220, "Sour Candy", ActorType::Candy, Accessibility::InGame },
    {1235, "Happy Candy", ActorType::Candy, Accessibility::InGame },
    {1236, "Joy Candy", ActorType::Candy, Accessibility::InGame },
    {1238, "Romance Candy", ActorType::Candy, Accessibility::InGame },
    {1283, "Slab Paving", ActorType::Paving, Accessibility::InGame },
    {1284, "Stone Paving", ActorType::Paving, Accessibility::InGame },
    {1285, "Block Paving", ActorType::Paving, Accessibility::InGame },
    {1286, "Crazy Paving", ActorType::Paving, Accessibility::InGame },
    {1288, "Cobblestones", ActorType::Paving, Accessibility::InGame },
    {1291, "Showbiz", ActorType::Paving, Accessibility::InGame },
    {1292, "Octagonal Paving", ActorType::Paving, Accessibility::InGame },
    {1306, "Raisant Site", ActorType::Shed, Accessibility::InGame },
    {1308, "Badgesicle Site", ActorType::Shed, Accessibility::InGame },
    {1309, "Sherbat Site", ActorType::Shed, Accessibility::InGame },
    {1310, "Fizzlybear Site", ActorType::Shed, Accessibility::InGame },
    {1311, "Sweetooth Site", ActorType::Shed, Accessibility::InGame },
    {1312, "Buzzlegum Site", ActorType::Shed, Accessibility::InGame },
    {1314, "Taffly Site", ActorType::Shed, Accessibility::InGame },
    {1315, "Flutterscotch Site", ActorType::Shed, Accessibility::InGame },
    {1316, "Twingersnap Site", ActorType::Shed, Accessibility::InGame },
    {1317, "Honey Hive Site", ActorType::Shed, Accessibility::InGame },
    {1318, "Galagoogoo Site", ActorType::Shed, Accessibility::InGame },
    {1319, "Buzzenge Site", ActorType::Shed, Accessibility::InGame },
    {1321, "Candary Site", ActorType::Shed, Accessibility::InGame },
    {1323, "Kittyfloss Site", ActorType::Shed, Accessibility::InGame },
    {1324, "Jameleon Site", ActorType::Shed, Accessibility::InGame },
    {1325, "Cluckles Site", ActorType::Shed, Accessibility::InGame },
    {1327, "Moozipan Site", ActorType::Shed, Accessibility::InGame },
    {1328, "Moozipan Shed Site", ActorType::Shed, Accessibility::InGame },
    {1329, "Cocoadile Site", ActorType::Shed, Accessibility::InGame },
    {1330, "Crowla Site", ActorType::Shed, Accessibility::InGame },
    {1331, "Doenut Site", ActorType::Shed, Accessibility::InGame },
    {1333, "Barkbark Site", ActorType::Shed, Accessibility::InGame },
    {1336, "Dragumfly Site", ActorType::Shed, Accessibility::InGame },
    {1337, "Quackberry Site", ActorType::Shed, Accessibility::InGame },
    {1339, "Eaglair Site", ActorType::Shed, Accessibility::InGame },
    {1341, "Elephanilla Site", ActorType::Shed, Accessibility::InGame },
    {1342, "Reddhott Site", ActorType::Shed, Accessibility::InGame },
    {1343, "Salamango Site", ActorType::Shed, Accessibility::InGame },
    {1345, "Pigxie Building Site", ActorType::Shed, Accessibility::InGame },
    {1346, "Pretztail Site", ActorType::Shed, Accessibility::InGame },
    {1347, "Lickatoad Site", ActorType::Shed, Accessibility::InGame },
    {1355, "Juicygoose Site", ActorType::Shed, Accessibility::InGame },
    {1357, "Syrupent Site", ActorType::Shed, Accessibility::InGame },
    {1361, "Fudgehog Site", ActorType::Shed, Accessibility::InGame },
    {1362, "Chippopotamus Site", ActorType::Shed, Accessibility::InGame },
    {1363, "Horstachio Site", ActorType::Shed, Accessibility::InGame },
    {1364, "Fourheads Site", ActorType::Shed, Accessibility::InGame },
    {1372, "Roario Site", ActorType::Shed, Accessibility::InGame },
    {1376, "Bonboon Site", ActorType::Shed, Accessibility::InGame },
    {1378, "Profitamole Site", ActorType::Shed, Accessibility::InGame },
    {1380, "Cinnamonkey Site", ActorType::Shed, Accessibility::InGame },
    {1382, "Mothdrop Site", ActorType::Shed, Accessibility::InGame },
    {1383, "Mousemallow Site", ActorType::Shed, Accessibility::InGame },
    {1384, "Newtgat Site", ActorType::Shed, Accessibility::InGame },
    {1390, "Parrybo Site", ActorType::Shed, Accessibility::InGame },
    {1393, "Rashberry Site", ActorType::Shed, Accessibility::InGame },
    {1394, "Pudgeon Site", ActorType::Shed, Accessibility::InGame },
    {1395, "Lackatoad Site", ActorType::Shed, Accessibility::InGame },
    {1397, "Ponocky Site", ActorType::Shed, Accessibility::InGame },
    {1399, "Bunnycomb Site", ActorType::Shed, Accessibility::InGame },
    {1400, "Macaraccoon Site", ActorType::Shed, Accessibility::InGame },
    {1411, "Goobaa Site", ActorType::Shed, Accessibility::InGame },
    {1412, "Goobaa Shed Site", ActorType::Shed, Accessibility::InGame },
    {1415, "Sparrowmint Site", ActorType::Shed, Accessibility::InGame },
    {1416, "Spider Site", ActorType::Shed, Accessibility::InGame },
    {1417, "Squazzil Site", ActorType::Shed, Accessibility::InGame },
    {1422, "Swanana Site", ActorType::Shed, Accessibility::InGame },
    {1429, "Chewnicorn Site", ActorType::Shed, Accessibility::InGame },
    {1436, "Mallowolf Site", ActorType::Shed, Accessibility::InGame },
    {1438, "Whirlm Site", ActorType::Shed, Accessibility::InGame },
    {1441, "Zumbug Site", ActorType::Shed, Accessibility::InGame },
    {1442, "Shellybean Site", ActorType::Shed, Accessibility::InGame },
    {1443, "Mine Site", ActorType::Shed, Accessibility::InGame },
    {1449, "Helper House Site", ActorType::Shed, Accessibility::InGame },
    {1454, "Daisy Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1455, "Buttercup Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1456, "Bluebell Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1457, "Poppy Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1458, "Sunflower Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1459, "Tulip Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1460, "Snapdragon Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1461, "Bird of Paradise Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1462, "Orchid Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1464, "Watercress Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1465, "Water Lily Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1466, "Bulrush Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1467, "Thistle Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1468, "Poison Ivy Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1470, "Venus Pinata Trap Flowerhead", ActorType::Flowerhead, Accessibility::InGame },
    {1488, "Carrot", ActorType::Veggie, Accessibility::InGame },
    {1489, "Turnip", ActorType::Veggie, Accessibility::InGame },
    {1491, "Pumpkin", ActorType::Veggie, Accessibility::InGame },
    {1492, "Chili", ActorType::Veggie, Accessibility::InGame },
    {1495, "Corn", ActorType::Veggie, Accessibility::InGame },
    {1501, "Raisant Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1502, "Badgesicle Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1503, "Sherbat Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1504, "Fizzlybear Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1505, "Sweetooth Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1506, "Buzzlegum Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1507, "Black Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1508, "Taffly Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1509, "Blue Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1510, "Twingersnap Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1511, "Brown Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1512, "Galagoogoo Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1513, "Buzzenge Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1514, "Candary Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1515, "Kittyfloss Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1516, "Jameleon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1517, "Cluckles Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1518, "Moozipan Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1519, "Cocoadile Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1520, "Crowla Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1521, "Doenut Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1522, "Barkbark Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1523, "Dragonache Life Candy", ActorType::LifeCandy, Accessibility::UnobtainableInGame },
    {1524, "Dragumfly Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1525, "Quackberry Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1526, "Eaglair Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1527, "Elephanilla Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1528, "Reddhott Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1529, "Salamango Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1530, "Pigxie Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1531, "Pretztail Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1532, "Lickatoad Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1533, "Raisant Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1535, "Juicygoose Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1536, "Syrupent Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1537, "Green Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1538, "Fudgehog Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1539, "Chippopotamus Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1540, "Horstachio Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1541, "Fourheads Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1542, "Roario Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1543, "Bonboon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1544, "Profitamole Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1545, "Cinnamonkey Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1546, "Mothdrop Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1547, "Mousemallow Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1548, "Newtgat Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1549, "Orange Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1550, "Parrybo Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1551, "Rashberry Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1552, "Pudgeon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1553, "Lackatoad Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1554, "Pink Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1555, "Ponocky Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1556, "Purple Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1557, "Bunnycomb Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1558, "Macaraccoon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1559, "Red Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1560, "Salamango Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1561, "Goobaa Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1562, "Sparrowmint Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1563, "Arocknid Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1564, "Squazzil Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1565, "Swanana Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1566, "Chewnicorn Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1567, "Sour Sherbat Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1568, "White Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1569, "Mallowolf Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1570, "Whirlm Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1571, "Yellow Flutterscotch Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1572, "Zumbug Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1574, "Sour Crowla Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1575, "Sour Macaraccoon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1576, "Sour Cocoadile Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1577, "Sour Profitamole Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1578, "Sour Mallowolf Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1579, "Sour Bonboon Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1580, "Shellybean Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1581, "Sour Shellybean Life Candy", ActorType::LifeCandy, Accessibility::InGame },
    {1585, "Lottie", ActorType::Shopkeeper, Accessibility::InGame },
    {1586, "Fannie", ActorType::Shopkeeper, Accessibility::InGame },
    {1587, "Doc Patchingo", ActorType::Shopkeeper, Accessibility::InGame },
    {1588, "Arfur", ActorType::Shopkeeper, Accessibility::InGame },
    {1589, "Willy", ActorType::Shopkeeper, Accessibility::InGame },
    {1590, "Miss Petula", ActorType::Shopkeeper, Accessibility::InGame },
    {1591, "Ivor Beggar", ActorType::Helper, Accessibility::InGame },
    {1592, "Bart", ActorType::Shopkeeper, Accessibility::InGame },
    {1593, "Gretchen", ActorType::Shopkeeper, Accessibility::InGame },
    {1600, "Red Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1601, "Yellow Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1602, "Blue Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1603, "Green Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1604, "Purple Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1605, "Orange Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1606, "Brown Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1607, "Cocoadile Tears Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1608, "Special Mix Fertilizer", ActorType::Tool, Accessibility::InGame },
    {1622, "Sprinkling Contract", ActorType::Contract, Accessibility::InGame },
    {1623, "Weedling Contract", ActorType::Contract, Accessibility::InGame },
    {1624, "Watchling1 Contract", ActorType::Contract, Accessibility::InGame },
    {1625, "Gatherling Contract", ActorType::Contract, Accessibility::InGame },
    {1626, "Diggerling Contract", ActorType::Contract, Accessibility::InGame },
    {1627, "Watchling2 Contract", ActorType::Contract, Accessibility::InGame },
    {1660, "Retro Disco Wig", ActorType::Assessory, Accessibility::InGame },
    {1661, "Breegull Carrier", ActorType::Assessory, Accessibility::InGame },
    {1662, "Shark Tooth Necklace", ActorType::Assessory, Accessibility::InGame },
    {1663, "Cool Shades", ActorType::Assessory, Accessibility::InGame },
    {1664, "Howdy Pardner Hat", ActorType::Assessory, Accessibility::InGame },
    {1665, "Doenut Stalker", ActorType::Assessory, Accessibility::InGame },
    {1670, "Yokel Teeth", ActorType::Assessory, Accessibility::InGame },
    {1672, "Yee-haw Hat", ActorType::Assessory, Accessibility::InGame },
    {1673, "Se or Sombrero", ActorType::Assessory, Accessibility::InGame },
    {1674, "Pillager's Helmet", ActorType::Assessory, Accessibility::InGame },
    {1675, "Thunder Cut", ActorType::Assessory, Accessibility::InGame },
    {1676, "Beanie Cap", ActorType::Assessory, Accessibility::InGame },
    {1677, "Weather-Girl Wig", ActorType::Assessory, Accessibility::InGame },
    {1678, "Diggerling Helmet Mk1", ActorType::Assessory, Accessibility::InGame },
    {1679, "Gas Mask", ActorType::Assessory, Accessibility::InGame },
    {1680, "Party Horns", ActorType::Assessory, Accessibility::InGame },
    {1682, "Caterpillars", ActorType::Assessory, Accessibility::InGame },
    {1684, "Super Hero Mask", ActorType::Assessory, Accessibility::InGame },
    {1685, "School Cap", ActorType::Assessory, Accessibility::InGame },
    {1686, "Baseball Cap", ActorType::Assessory, Accessibility::InGame },
    {1688, "Tiara of Tranquility", ActorType::Assessory, Accessibility::InGame },
    {1689, "Slim Tache", ActorType::Assessory, Accessibility::InGame },
    {1690, "Spiked Collar", ActorType::Assessory, Accessibility::InGame },
    {1691, "Geek Glasses", ActorType::Assessory, Accessibility::InGame },
    {1692, "Reporter's Camera", ActorType::Assessory, Accessibility::InGame },
    {1693, "Bling Teeth", ActorType::Assessory, Accessibility::InGame },
    {1694, "Bow", ActorType::Assessory, Accessibility::InGame },
    {1695, "Fez", ActorType::Assessory, Accessibility::InGame },
    {1696, "Fake Winner's Rosette", ActorType::Assessory, Accessibility::InGame },
    {1697, "Diamond Choker", ActorType::Assessory, Accessibility::InGame },
    {1698, "Blackeye Patch", ActorType::Assessory, Accessibility::InGame },
    {1699, "Tap Shoes", ActorType::Assessory, Accessibility::InGame },
    {1700, "Ballet Shoes", ActorType::Assessory, Accessibility::InGame },
    {1701, "Crown", ActorType::Assessory, Accessibility::InGame },
    {1702, "Handlebar Mustache", ActorType::Assessory, Accessibility::InGame },
    {1703, "Football Helmet", ActorType::Assessory, Accessibility::InGame },
    {1704, "Sweaty Wrist Band", ActorType::Assessory, Accessibility::InGame },
    {1705, "Bling Bangle", ActorType::Assessory, Accessibility::InGame },
    {1706, "Beaded Wig", ActorType::Assessory, Accessibility::InGame },
    {1708, "Secret Agent Bowtie", ActorType::Assessory, Accessibility::InGame },
    {1709, "Bling Bracelet", ActorType::Assessory, Accessibility::InGame },
    {1710, "Crystal Broach", ActorType::Assessory, Accessibility::InGame },
    {1711, "Bunnycomb Ears", ActorType::Assessory, Accessibility::InGame },
    {1712, "Bushy Moustache", ActorType::Assessory, Accessibility::InGame },
    {1713, "Cook Hat", ActorType::Assessory, Accessibility::InGame },
    {1714, "The Von Ghoul", ActorType::Assessory, Accessibility::InGame },
    {1715, "Yee-haw Boots", ActorType::Assessory, Accessibility::InGame },
    {1716, "Butcha's", ActorType::Assessory, Accessibility::InGame },
    {1717, "Diamond Necklace", ActorType::Assessory, Accessibility::InGame },
    {1718, "Combat Boots", ActorType::Assessory, Accessibility::InGame },
    {1720, "Romance Earrings", ActorType::Assessory, Accessibility::InGame },
    {1721, "Mermaid Earrings", ActorType::Assessory, Accessibility::InGame },
    {1722, "Big Bling Earrings", ActorType::Assessory, Accessibility::InGame },
    {1724, "Big Jolly Lips", ActorType::Assessory, Accessibility::InGame },
    {1725, "Comedian's Nose", ActorType::Assessory, Accessibility::InGame },
    {1726, "Buck Teeth", ActorType::Assessory, Accessibility::InGame },
    {1728, "Soccer Boots", ActorType::Assessory, Accessibility::InGame },
    {1729, "Squazzil Hat", ActorType::Assessory, Accessibility::InGame },
    {1730, "DanceGlow", ActorType::Assessory, Accessibility::InGame },
    {1731, "Pendant Necklace", ActorType::Assessory, Accessibility::InGame },
    {1732, "Halo of Hardness", ActorType::Assessory, Accessibility::InGame },
    {1733, "Safety Helmet", ActorType::Assessory, Accessibility::InGame },
    {1734, "Sweaty Head Band", ActorType::Assessory, Accessibility::InGame },
    {1735, "Breegull Waders", ActorType::Assessory, Accessibility::InGame },
    {1737, "Leafos Medallion", ActorType::Assessory, Accessibility::InGame },
    {1739, "Toff Monocle", ActorType::Assessory, Accessibility::InGame },
    {1740, "Astro-Walkers", ActorType::Assessory, Accessibility::InGame },
    {1741, "Halloween Bolts", ActorType::Assessory, Accessibility::InGame },
    {1742, "Bling Nose-Ring", ActorType::Assessory, Accessibility::InGame },
    {1743, "Dellmonty", ActorType::Assessory, Accessibility::InGame },
    {1745, "Mermaid Necklace", ActorType::Assessory, Accessibility::InGame },
    {1747, "Tussle Tricorn", ActorType::Assessory, Accessibility::InGame },
    {1748, "Rashberry Hat", ActorType::Assessory, Accessibility::InGame },
    {1749, "Rashberry Helmet", ActorType::Assessory, Accessibility::InGame },
    {1750, "Reading Glasses", ActorType::Assessory, Accessibility::InGame },
    {1751, "Red Nose", ActorType::Assessory, Accessibility::InGame },
    {1752, "Robber's Mask", ActorType::Assessory, Accessibility::InGame },
    {1753, "Extreme Sports Goggles", ActorType::Assessory, Accessibility::InGame },
    {1754, "Santa Hat", ActorType::Assessory, Accessibility::InGame },
    {1755, "Non-Resident Scarf", ActorType::Assessory, Accessibility::InGame },
    {1756, "Sea-Shell Collar", ActorType::Assessory, Accessibility::InGame },
    {1757, "Bunnycomb Slippers", ActorType::Assessory, Accessibility::InGame },
    {1758, "Snow Shoes", ActorType::Assessory, Accessibility::InGame },
    {1759, "Belly-Splash Specials", ActorType::Assessory, Accessibility::InGame },
    {1760, "Granny's Tache", ActorType::Assessory, Accessibility::InGame },
    {1761, "Funky Tie", ActorType::Assessory, Accessibility::InGame },
    {1762, "Conga's Top Hat", ActorType::Assessory, Accessibility::InGame },
    {1763, "Breegull Turbo Trainers", ActorType::Assessory, Accessibility::InGame },
    {1765, "Dastardos Scarf", ActorType::Assessory, Accessibility::InGame },
    {1766, "Bell", ActorType::Assessory, Accessibility::InGame },
    {1767, "Bonnet", ActorType::Assessory, Accessibility::InGame },
    {1768, "Buzzlegum Keeper Hat", ActorType::Assessory, Accessibility::InGame },
    {1769, "Buttercup Hair Flower", ActorType::Assessory, Accessibility::InGame },
    {1770, "Daisy Hair Flower", ActorType::Assessory, Accessibility::InGame },
    {1771, "Bling Earrings", ActorType::Assessory, Accessibility::InGame },
    {1772, "Not-so-Bling Earrings", ActorType::Assessory, Accessibility::InGame },
    {1773, "Pendant Earrings", ActorType::Assessory, Accessibility::InGame },
    {1774, "Pearly Bracelet", ActorType::Assessory, Accessibility::InGame },
    {1775, "Poppy Hair Flower", ActorType::Assessory, Accessibility::InGame },
    {1777, "Sunflower Hair Flower", ActorType::Assessory, Accessibility::InGame },
    {1778, "Student's Hat", ActorType::Assessory, Accessibility::InGame },
    {1779, "Comedian's Choice", ActorType::Assessory, Accessibility::InGame },
    {1780, "Strong 'n' Macho", ActorType::Assessory, Accessibility::InGame },
    {1781, "Soupswill Cook Hat", ActorType::Assessory, Accessibility::InGame },
    {1782, "Tail Bow", ActorType::Assessory, Accessibility::InGame },
    {1783, "Super Hero Belt", ActorType::Assessory, Accessibility::InGame },
    {1784, "Fruity Hat", ActorType::Assessory, Accessibility::InGame },
    {1785, "Mr. Pants Hat", ActorType::Assessory, Accessibility::InGame },
    {1786, "Sailor Hat", ActorType::Assessory, Accessibility::InGame },
    {1787, "Conkerific Helmet", ActorType::Assessory, Accessibility::InGame },
    {1788, "Vela Wig", ActorType::Assessory, Accessibility::InGame },
    {1789, "Juno Helmet", ActorType::Assessory, Accessibility::InGame },
    {1790, "Grunty Hat", ActorType::Assessory, Accessibility::InGame },
    {1791, "Jam-Jars Hat", ActorType::Assessory, Accessibility::InGame },
    {1792, "Binner's Hat", ActorType::Assessory, Accessibility::InGame },
    {1793, "Princess Hat", ActorType::Assessory, Accessibility::InGame },
    {1794, "Von Ghoul Helmet", ActorType::Assessory, Accessibility::InGame },
    {1795, "Sabreman Helmet", ActorType::Assessory, Accessibility::InGame },
    {1796, "Ortho's Spare Hat", ActorType::Assessory, Accessibility::InGame },
    {1797, "Knight Helmet", ActorType::Assessory, Accessibility::InGame },
    {1798, "Headphones", ActorType::Assessory, Accessibility::InGame },
    {1799, "Jiggy Earrings", ActorType::Assessory, Accessibility::InGame },
    {1800, "Lupus Ears", ActorType::Assessory, Accessibility::InGame },
    {1801, "Disco Shades", ActorType::Assessory, Accessibility::InGame },
    {1802, "Flying Goggles", ActorType::Assessory, Accessibility::InGame },
    {1803, "Bottles' Glasses", ActorType::Assessory, Accessibility::InGame },
    {1804, "Romantic Flower", ActorType::Assessory, Accessibility::InGame },
    {1805, "Battletoad Bracelets", ActorType::Assessory, Accessibility::InGame },
    {1806, "Prisoner Bracelet", ActorType::Assessory, Accessibility::InGame },
    {1807, "Rashberry Badge", ActorType::Assessory, Accessibility::InGame },
    {1808, "Clockwork Key", ActorType::Assessory, Accessibility::InGame },
    {1809, "Kameo Wings", ActorType::Assessory, Accessibility::InGame },
    {1810, "Fake Fin", ActorType::Assessory, Accessibility::InGame },
    {1811, "Flamenco Shoes", ActorType::Assessory, Accessibility::InGame },
    {1812, "Ash Slippers", ActorType::Assessory, Accessibility::InGame }
};


inline static void OnStartupPatch()
{
//apply g_FixCrates
	//MemHelp::SetPatch(g_FixCrates, true);

}

